(function(d){var b=window.AmazonUIPageJS||window.P,e=b._namespace||b.attributeErrors,c=e?e("PortableOffersDisplayAssets@core","PortableOffersDisplayAssets"):b;c.guardFatal?c.guardFatal(d)(c,window):c.execute(function(){d(c,window)})})(function(d,b,e){d.when("ax:initiator","action-handler:dom-input-parser").register("cta-handler",function(c,b){function a(a){c.initiateCTAHandling(a,(1<arguments.length&&arguments[1]!==e?arguments[1]:null)||b.createRequestPayload(a))}return{handleATCClick:a,handleCTAClick:a}});
"use strict";d.register("pcta:bottom-sheet-constants",function(){return{EVENTS:{AFTER_SHOW:"a:sheet:afterShow:",AFTER_HIDE:"a:sheet:afterHide:"}}});"use strict";d.register("pcta:utils:csm",function(){function c(a,c){b.ue&&b.ue.count&&b.ue.count(a,c)}function g(){try{var a=document.querySelector('input[name\x3d"referrer"]');return a&&a.value?a.value.trim():"unknownPageType"}catch(k){return"pageType:extraction:error"}}return{logCounter:c,logPerformance:function(a){performance&&performance.now&&c(a,
b.parseInt(performance.now()))},logCounterWithPageContext:function(a,b){var d=g();c(a+":"+d,b)},logPerformanceWithPageContext:function(a){var d=g();if(performance&&performance.now){var f=b.parseInt(performance.now());c(a+":"+d,f)}},getPageTypeForMetrics:g}});"use strict";d.register("action-handler:dom-input-parser",function(){return{createRequestPayload:function(c){var b={};var a=c.$target.attr("form");a=document.getElementById(a);var d=c.$target.closest("form");if(a=a?a:0<d.length?d[0]:null){d=a.elements;
for(var f=0;f<d.length;f++){var e=d[f];e.name&&(b[e.name]=e.value)}(a=a.getAttribute("action")||a.action)&&(b.formAction=a)}c=c.data;for(var h in c)c.hasOwnProperty(h)&&(b[h]=c[h]);return b}}});"use strict";d.register("pcta:utils:iframe",function(){return{isIframe:function(){return b!==b.parent},isCTAHandlerOnParentWindow:function(){if(this.isIframe()&&b.parent&&b.parent.P){var c=!1;b.parent.P.now("cta-handler").execute(function(b){c=!!b});return c}return!1}}})});
/* ******** */
'use strict';(function(y){var w=window.AmazonUIPageJS||window.P,C=w._namespace||w.attributeErrors,A=C?C("PortableVariableWeightAssets",""):w;A.guardFatal?A.guardFatal(y)(A,window):A.execute(function(){y(A,window)})})(function(y,w,C){function A(c){var f=!1;y.now(c).execute("pvwDuplicationGuard",function(n){f=!!n});return f}function ca(c,f){if(!A(c))try{y.register(c,f)}catch(n){if(!n.message.includes("reregistered by PortableVariableWeightAssets"))throw n;}}function da(){var c=arguments;return{register:function(f,
n){if(!A(f))try{y.when.apply(y,c).register(f,n)}catch(l){if(!l.message.includes("reregistered by PortableVariableWeightAssets"))throw l;}},execute:function(f,n){y.when.apply(y,c).execute(f,n)}}}function Ia(c,f){if(!c)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!f||"object"!==typeof f&&"function"!==typeof f?c:f}function Ja(c,f){if("function"!==typeof f&&null!==f)throw new TypeError("Super expression must either be null or a function, not "+typeof f);
c.prototype=Object.create(f&&f.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});f&&(Object.setPrototypeOf?Object.setPrototypeOf(c,f):c.__proto__=f)}function xa(c,f){if(!(c instanceof f))throw new TypeError("Cannot call a class as a function");}ca("PVWDuplicationGuard",function(){return{register:ca,when:da}});"use strict";y.when("PVWDuplicationGuard").execute("pvw-constants-registration",function(c){c.register("pvw-constants",function(){return{ITEM_HEIGHT:40,SCROLL_DELAY:100,
SHEET_HEIGHT:355,SHEET_NAME:"pvw_bottom_sheet",DECIMAL_SEPARATOR:".",PRECISION_DEFAULT:2,MODE:{ATC:"atc",ATD:"atd"},UNITS:{GRAMS:"GRAMS",KILOGRAMS:"KILOGRAMS",OUNCES:"OUNCES",POUNDS:"POUNDS",GRAM_SYMBOL:"g",POUND_SYMBOL:"lb",KILOGRAM_SYMBOL:"kg",OUNCES_SYMBOL:"oz",UNIT_SYMBOL_MAP:{GRAMS:"g",KILOGRAMS:"kg",OUNCES:"oz",POUNDS:"lb"}},METRICS:{SHOW_POPUP:"showPopup",TRIGGER_DECLARATIVE_ACTION:"triggerDeclarativeAction"},SUCCESS:!0,FAILURE:!1,MOBILE:!0,DESKTOP:!1,PVW_CONTAINER:".vw-container",PVW_REPLACE:".pvw-replace",
TEMPLATE_VERSION:{V1:"V1",V2:"V2"},TEMPLATE_REPLACE_STRING:{QUANTITY:"{quantity}",ESTIMATE:"{estimate}",REPLACE:"{replace}"}}})});"use strict";y.when("PVWDuplicationGuard").execute("pvw-bottom-sheet-registration",function(c){c.when("A","a-sheet","portable-variable-weight-view-model","pvw-state-factory","pvw-content-manager","pvw-constants","pvw-bs-translations","pvw-csm-util").register("pvw-bottom-sheet",function(f,n,l,r,g,e,u,v){function q(e){x.currentQuantity=e}var x=null,c=null,D=f.now();v.logLatencyMetric("-JSReady",
D,e.MOBILE);return{openSheet:function(q,S){f.$(".a-sheet-lightbox").click();f.on("a:sheet:afterHide",function K(n){n.sheet._name!==e.SHEET_NAME&&(c=n.sheet);f.off("a:sheet:afterHide",K)});setTimeout(function(){try{x=r.createInitialState(q,S);var f=l.getMobileContent(x),c=n.get(e.SHEET_NAME);if(c)g.setContent(c.getContentContainer(),f);else{var L={name:e.SHEET_NAME,inlineContent:f,height:e.SHEET_HEIGHT};x.templateVersion===e.TEMPLATE_VERSION.V2?(L.closeType="icon",L.heading=u.selectQuantityText):(L.closeType=
"message",L.closeMessage=u.cancelMessage);var z=n.create(L);v.incrementInitializeCount(!0,!0);c=z}n.showSheet(c)}catch(t){throw v.incrementShowPopup(e.FAILURE,e.MOBILE),t;}v.incrementShowPopup(e.SUCCESS,e.MOBILE)})},afterSheetShow:function(e){g.cacheElements(e.sheet.$contentContainer);g.selectItem(x.currentQuantity,x);g.setupScrollHandler(x,q)},handleSheetClose:function(){var l=n.get(e.SHEET_NAME);g.removeAllContent(l.getContentContainer());x=null;c&&(f.trigger("pvw-bottom-sheet:afterClosed",{previousSheetName:c._name}),
c=null)},handleATCClick:function(f){f.$event.preventDefault();try{x.ctaButtonClickCallback(x.currentQuantity),n.hideSheet(n.get(e.SHEET_NAME))}catch(ha){throw v.incrementTriggerDeclarativeActionCount(f.action,e.FAILURE,e.MOBILE),ha;}v.incrementTriggerDeclarativeActionCount(f.action,e.SUCCESS,e.MOBILE)},getAUISheetName:function(){return e.SHEET_NAME}}})});"use strict";y.when("PVWDuplicationGuard").execute("pvw-drop-down-registration",function(c){c.when("A","a-dropdown","portable-variable-weight-view-model",
"pvw-state-factory","pvw-constants","pvw-csm-util","pvw-weight-utils","pvw-pricing-utils","pvw-bs-translations","pvw-dropdown-footer").register("pvw-drop-down",function(f,n,l,c,g,e,u,v,q,x){function r(e,l,c){var g="a:popover:hide:"+c;f.on("a:dropdown:popover:open:pvw-dropdown-"+c,function(e){e=e.closest(".a-popover");n.setFooterContent(e,x.createFooterFragment())});f.on(g,function(f){y(e,l)})}function D(e,n,l,c){var g="a:dropdown:selected:"+l;f.off(g);f.on(g,function(l){c(parseFloat(l.value));y(e,
n);f.off(g)})}function y(e,f){f.hide();e.show();e=e.find('[role\x3d"combobox"]');e.length&&e.focus()}function w(e,f){f=q.aboutLowerCase.replace(g.TEMPLATE_REPLACE_STRING.ESTIMATE,f);return{html:e+' \x3cspan class\x3d"a-color-tertiary"\x3e'+f+"\x3c/span\x3e",text:e+" "+f}}function C(e){A=c.createInitialState(e,null);var f=e.estimateAverageSizeUnitOfMeasureUnit?u.getWeightUnitSymbol(e.estimateAverageSizeUnitOfMeasureUnit):u.getWeightUnitSymbol(e.pricingUnitOfMeasureUnit);return A.selectorValues.map(function(n,
l){if(e.isItemSoldByCount){var c=A.selectorValues.at(l);c=w(c,u.formatWeight(e.estimateAverageSize*c,f,g.PRECISION_DEFAULT,e.decimalSeparator))}else{c=A.selectorDisplayValues.at(l);var q=A.selectorValues.at(l);l=v.isNonFractionalCurrency(e.currencyCode||e.pricePerUnitMoneyCurrencyCode);q=v.calculatePrice(e.pricePerSingleUnitAmount,q,l);l=v.formatPriceForDisplay(q,e.currencySymbol,l,e.currencySymbolPosition||"Left",e.decimalSeparator);c=w(c,l)}return{value:n,displayValue:c.html,displayText:c.text}})}
var A=null,K=f.now();e.logLatencyMetric("-JSReady",K,g.DESKTOP);return{openDropdown:function(e,c,g,q,u){0==q.length?(q=C(e),q=f.$(l.getDesktopContent({asin:u,selectedOption:e.currentQuantity,dropdownOptions:q})),g.parent().prepend(q),r(g,q,u)):(e=e.currentQuantity)&&q&&n.getSelect(q.find("select.a-native-dropdown")).setValue(e);D(g,q,u,c);c=q;c.show();g.hide();c.find("select.a-native-dropdown").click()}}})});"use strict";y.when("PVWDuplicationGuard").execute("pvw-dropdown-footer-registration",function(c){c.when("pvw-bs-translations").register("pvw-dropdown-footer",
function(f){return{createFooterFragment:function(){var c=new DocumentFragment,l=document.createElement("div");l.className="pvw-dropdown-footer-inner";var r='\x3cspan\x3e\x3cdiv class\x3d"a-color-secondary a-text-bold"\x3e'+f.variableWeightDisclaimer.replace(/\./,"")+"\x3c/div\x3e\x3c/span\x3e";l.innerHTML=r;c.append(l);return c}}})});"use strict";y.when("PVWDuplicationGuard").execute("pvw-expanded-stepper-registration",function(c){c.when("pvw-text-replace").register("pvw-expanded-stepper",function(f){return{setExpandedStepperWithRegulatoryText:function(c,
l,r,g){g&&c.setValueWithStepperDisplays?(g=f.createRegulatoryDisplayDocumentFragment(r,g),c.setValueWithStepperDisplays(r,l,g)):c.setValueWithDisplayString(r,l)}}})});"use strict";y.when("PVWDuplicationGuard").execute("pvw-state-factory-registration",function(c){c.when("pvw-weight-utils","pvw-bs-translations","pvw-constants","pvw-text-replace").register("pvw-state-factory",function(f,c,l,r){function g(e){return e.map(function(e){e=1===e?c.itemText.replace(l.TEMPLATE_REPLACE_STRING.QUANTITY,e):c.itemsText.replace(l.TEMPLATE_REPLACE_STRING.QUANTITY,
e);return e})}return{createInitialState:function(e,n){for(var v=e.sellingMax,q=e.sellingIncrement,x=[],u=e.sellingMin;u<=v;)x.push(u),u+=q,u=parseFloat(u.toFixed(2));v=f.getWeightUnitSymbol(e.pricingUnitOfMeasureUnit||e.sellingUnitOfMeasureUnit);u=e.currencySymbolPosition&&"right"===e.currencySymbolPosition.toLowerCase()?"Right":"Left";var D=e.currentQuantity||e.sellingMin||1;q=e.templateVersion||l.TEMPLATE_VERSION.V2;var y=e.mode||l.MODE.ATC;if(y===l.MODE.ATD){var w=e.decimalSeparator;var A=D.toFixed(1);
w&&"."!==w&&(A=A.replace(".",w));w=c.addToDeliveryButtonText.replace("{qty}",A).replace("{unit}",v)}else w=e.currentQuantity?q===l.TEMPLATE_VERSION.V2?c.updateQuantityText:c.updateCartButtonText:c.addToCartButtonText;n={isItemSoldByCount:e.isItemSoldByCount,currentQuantity:D,selectorValues:x,pricePerUnitAmount:e.pricePerSingleUnitAmount,pricePerUnitDisplayString:e.pricePerUnitDisplayString,priceSymbol:e.currencySymbol,pricingUnitOfMeasureUnit:e.pricingUnitOfMeasureUnit,currencySymbolPosition:u,currencyCode:e.pricePerUnitMoneyCurrencyCode,
priceDecimalSeparator:e.decimalSeparator,ctaButtonClickCallback:n,itemWeightUnit:v,asinImageUrl:e.imageUrl,isSoldByUnit:e.isItemSoldByCount,summaryDisclaimerText:c.summaryDisclaimerText,selectQuantityText:c.selectQuantityText,summaryAtcButtonText:w,estSingleItemWeight:e.estimateAverageSize,estimateAverageSizeUnitOfMeasureUnit:e.estimateAverageSizeUnitOfMeasureUnit,sellingMin:e.sellingMin,estTotalPriceText:c.estTotalPriceText,disclaimerText:c.variableWeightDisclaimer,aboutEstimationText:r.generateAboutEstimationText(D,
e),templateVersion:q,mode:y};e.isItemSoldByCount?(n.quantitySelectorUnitText=c.quantitySelectorUnitText,n.selectorDisplayValues=q===l.TEMPLATE_VERSION.V2?g(x):x,n.estTotalWeightText=c.estTotalWeightText):n.selectorDisplayValues=f.formatWeightsForDisplay(x,v,l.PRECISION_DEFAULT,n.priceDecimalSeparator);return n}}})});"use strict";y.when("PVWDuplicationGuard").execute("pvw-content-manager-registration",function(c){c.when("A","pvw-pricing-utils","pvw-weight-utils","pvw-constants","pvw-text-replace").register("pvw-content-manager",
function(c,n,l,r,g){function e(e,c){var q=c.selectorValues.indexOf(e);if(-1!==q){(c.templateVersion===r.TEMPLATE_VERSION.V2?f.pickerV2:f.picker).scrollTop(q*r.ITEM_HEIGHT);q=n.isNonFractionalCurrency(c.currencyCode);var v=l.calculateEstWeight(e,c.estSingleItemWeight,c.isItemSoldByCount),u=n.calculatePrice(c.pricePerUnitAmount,v,q);c.isItemSoldByCount&&f.estItemWeight.html(v);f.priceWhole.html(u.whole);q?f.priceFraction.html(""):f.priceFraction.html(10>u.fraction?"0"+u.fraction:u.fraction);c.templateVersion===
r.TEMPLATE_VERSION.V2&&(e=g.generateAboutEstimationText(e,{estimateAverageSize:c.estSingleItemWeight,currencySymbol:c.priceSymbol,pricePerSingleUnitAmount:c.pricePerUnitAmount,sellingMin:c.sellingMin,isItemSoldByCount:c.isItemSoldByCount,pricingUnitOfMeasureUnit:c.pricingUnitOfMeasureUnit,currencySymbolPosition:c.currencySymbolPosition,pricePerUnitMoneyCurrencyCode:c.currencyCode,decimalSeparator:c.priceDecimalSeparator,estimateAverageSizeUnitOfMeasureUnit:c.estimateAverageSizeUnitOfMeasureUnit}),
f.aboutEstText.html(e))}}var f;return{setContent:function(e,c){e.html(c)},cacheElements:function(e){f={picker:e.find(".pvw-scroll-picker"),estItemWeight:e.find(".pvw-bs-item-weight"),priceWhole:e.find(".a-price-whole"),priceFraction:e.find(".a-price-fraction"),aboutEstText:e.find(".pvw-about-est-text"),pickerV2:e.find(".pvw-scroll-picker-v2")};f.pickerV2&&f.pickerV2.length&&(f.pickerV2.find(".pvw-scroll-picker-item-v2").first().attr("aria-selected","true"),c.$(".a-sheet-heading").attr("id","a-sheet-heading-id"),
f.pickerV2.attr("aria-labelledby","a-sheet-heading-id"))},setupScrollHandler:function(c,l){var g=void 0,n=c.templateVersion===r.TEMPLATE_VERSION.V2?f.pickerV2:f.picker;n.scroll(function(){clearTimeout(g);g=setTimeout(function(){var g=n.scrollTop();g=Math.round(g/r.ITEM_HEIGHT);var q=c.selectorValues[g];e(q,c,l);l(q);f.pickerV2&&f.pickerV2.length&&f.pickerV2.find(".pvw-scroll-picker-item-v2").removeAttr("aria-selected").eq(g).attr("aria-selected","true")},r.SCROLL_DELAY)})},selectItem:e,removeAllContent:function(e){e.empty()}}})});
"use strict";var P=function(){return function(c,f){if(Array.isArray(c))return c;if(Symbol.iterator in Object(c)){var n=[],l=!0,r=!1,g=C;try{for(var e=c[Symbol.iterator](),u;!(l=(u=e.next()).done)&&(n.push(u.value),!f||n.length!==f);l=!0);}catch(v){r=!0,g=v}finally{try{if(!l&&e["return"])e["return"]()}finally{if(r)throw g;}}return n}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}(),ya=function(){function c(c,n){for(var f=0;f<n.length;f++){var r=n[f];r.enumerable=r.enumerable||
!1;r.configurable=!0;"value"in r&&(r.writable=!0);Object.defineProperty(c,r.key,r)}}return function(f,n,l){n&&c(f.prototype,n);l&&c(f,l);return f}}(),ka="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"===typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c};y.when("PVWDuplicationGuard").execute("portable-variable-weight-view-model-registration",function(c){c.register("portable-variable-weight-view-model",
function(){var c;(function(){function f(b,a,p,m){return b.substring(0,a)+m+b.substring(p)}function l(b){if(!b||!b.styleCodeString||1>b.styleCodeArray.length)return!1;var a=!1;return b.styleCodeArray.every(function(b){return""===b||"."===b||!!function(a){return La.some(function(b){return a.startsWith(b)})}(b)&&(!a&&function(a){return la.some(function(b){return a.startsWith(b)})}(b)&&(a=!0),!0)})&&a}function r(b){var a=Ma.exec(b);if(a&&a[0]&&a[1]&&a[2]&&a[3]&&a[1].startsWith("images/"))return{sourceUrl:b,
path:a[1],styleCodeString:a[2],styleCodeArray:a[2].split("_"),extension:a[3],queryString:a[4]}}function g(b,a,p){return b.queryString?a+"\x26aicid\x3d"+p:a+"?aicid\x3d"+p}function e(b){switch(b){case "Unspecified":return"unspecified";case "Normal":return"normal";case "Selected":return"selected";case "Disabled":return"disabled";case "Error":return"error";case "Warning":return"warning";case "Inactive":return"inactive";default:return b}}function u(b){switch(b){case "Unspecified":return"unspecified";
case "Left":return"left";case "Right":return"right";case "Center":return"center";default:return b}}function v(b){switch(b){case "TriggerRight":return"triggerRight";case "TriggerLeft":return"triggerLeft";case "TriggerBottom":return"triggerBottom";case "TriggerTop":return"triggerTop";case "TriggerVertical":return"triggerVertical";case "TriggerHorizontal":return"triggerHorizontal";case "TriggerVerticalAlignLeft":return"triggerVerticalAlignLeft";default:return b}}function q(b){switch(b){case "Button":return"button";
case "Submit":return"submit";case "Reset":return"reset";default:return b}}function x(b){switch(b){case "Unspecified":return"unspecified";case "Thumbnail":return"thumbnail";case "Supplemental":return"supplemental";case "Dropdown":return"dropdown";default:return b}}function y(b){switch(b){case "Unspecified":return"unspecified";case "First":return"first";case "Last":return"last";case "OnlyChild":return"onlychild";default:return b}}function w(b){switch(b){case "Unspecified":return"unspecified";case "None":return"none";
case "Micro":return"micro";case "Mini":return"mini";case "Small":return"small";case "Base":return"base";case "Medium":return"medium";case "MediumPlus":return"medium-plus";case "Large":return"large";case "ExtraLarge":return"extra-large";case "ExtraLargePlus":return"extra-large-plus";case "DoubleLarge":return"double-large";case "Block":return"block";default:return b}}function A(b){switch(b){case "Unspecified":return"unspecified";case "Micro":return"micro";case "Mini":return"mini";case "Small":return"small";
case "Base":return"base";case "Medium":return"medium";case "MediumPlus":return"medium-plus";case "Large":return"large";case "ExtraLarge":return"extra-large";case "ExtraLargePlus":return"extra-large-plus";default:return b}}function ha(b){switch(b){case "Unspecified":return"unspecified";case "ButtonBesideText":return"button-beside-text";default:return b}}function ca(b){switch(b){case "Unspecified":return"unspecified";case "Primary":return"primary";case "Search":return"search";case "BuyNow":return"buynow";
case "BuyNowPreorder":return"buynow-preorder";case "Cart":return"cart";case "OneClick":return"oneclick";case "OneClickPreorder":return"oneclick-preorder";case "Preorder":return"preorder";case "Sns":return"sns";case "Thumbnail":return"thumbnail";case "Toggle":return"toggle";case "ToggleUnavailable":return"toggle-unavailable";default:return b}}function da(b){return null!=b&&""!==b}function K(b){b=b.join(" ").split(" ").filter(da).join(" ");return 0<b.length?b:void 0}function L(b,a){var p={},m;for(m in a+=
"-",b){var h=b,e=m;(h.hasOwnProperty?h.hasOwnProperty(e):h.containsKey(e))&&m.startsWith(a)&&(p[m.slice(a.length)]=b[m])}return p}function z(b,a,p){if(p){var m=p.hasOwnProperty?Object.keys(p):!(h=p.keySet()).map&&Java.from?Java.from(h):h;for(h=0;h<m.length;h++)b[a+m[h]]=p[m[h]]}var h;return b}function t(b,a){return a.content}function Ka(b){return null!=b&&""!==b}function ia(b){b=b.join(" ").split(" ").filter(Ka).join(" ");return 0<b.length?b:void 0}function ja(b,a){var p={},m;for(m in a+="-",b){var h=
b,e=m;(h.hasOwnProperty?h.hasOwnProperty(e):h.containsKey(e))&&m.startsWith(a)&&(p[m.slice(a.length)]=b[m])}return p}function F(b,a,p){if(p){var m=p.hasOwnProperty?Object.keys(p):!(h=p.keySet()).map&&Java.from?Java.from(h):h;for(h=0;h<m.length;h++)b[a+m[h]]=p[m[h]]}var h;return b}function Na(b){return null!=b&&""!==b}function za(b,a){var p={},m;for(m in a+="-",b){var h=b,e=m;(h.hasOwnProperty?h.hasOwnProperty(e):h.containsKey(e))&&m.startsWith(a)&&(p[m.slice(a.length)]=b[m])}return p}function ma(b,
a,p){if(p){var m=p.hasOwnProperty?Object.keys(p):!(h=p.keySet()).map&&Java.from?Java.from(h):h;for(h=0;h<m.length;h++)b[a+m[h]]=p[m[h]]}var h;return b}function Oa(b){switch(b){case "Unspecified":return"unspecified";case "Micro":return"micro";case "Mini":return"mini";case "Small":return"small";case "Base":return"base";case "BasePlus":return"base-plus";case "Medium":return"medium";case "MediumPlus":return"medium-plus";case "Large":return"large";case "ExtraLarge":return"extra-large";case "DoubleLarge":return"double-large";
default:return b}}function Pa(b){switch(b){case "Unspecified":return"unspecified";case "Base":return"base";case "Secondary":return"secondary";case "Tertiary":return"tertiary";case "State":return"state";case "Link":return"link";case "Inverse":return"inverse";case "Price":return"price";case "Attainable":return"attainable";case "Error":return"error";case "Warning":return"warning";case "Information":return"information";case "Success":return"success";default:return b}}function Qa(b){switch(b){case "Unspecified":return"unspecified";
case "TextBesideButton":return"text-beside-button";case "Offscreen":return"offscreen";default:return b}}function Ra(b){return null!=b&&""!==b}function Aa(b,a){var p={},m;for(m in a+="-",b){var h=b,e=m;(h.hasOwnProperty?h.hasOwnProperty(e):h.containsKey(e))&&m.startsWith(a)&&(p[m.slice(a.length)]=b[m])}return p}function na(b,a,p){if(p){var m=p.hasOwnProperty?Object.keys(p):!(h=p.keySet()).map&&Java.from?Java.from(h):h;for(h=0;h<m.length;h++)b[a+m[h]]=p[m[h]]}var h;return b}function oa(b,a,p){if(p){var m=
p.hasOwnProperty?Object.keys(p):!(h=p.keySet()).map&&Java.from?Java.from(h):h;for(h=0;h<m.length;h++)b[a+m[h]]=p[m[h]]}var h;return b}function Ba(b){switch(b){case "Unspecified":return"unspecified";case "Base":return"base";case "Secondary":return"secondary";case "Tertiary":return"tertiary";case "Price":return"price";default:return b}}function Sa(b){return null!=b&&""!==b}function N(b){b=b.join(" ").split(" ").filter(Sa).join(" ");return 0<b.length?b:void 0}function G(b,a,p){if(p){var m=p.hasOwnProperty?
Object.keys(p):!(h=p.keySet()).map&&Java.from?Java.from(h):h;for(h=0;h<m.length;h++)b[a+m[h]]=p[m[h]]}var h;return b}function pa(b){return b.reduce(function(a,b){return a.concat(Array.isArray(b)?pa(b):b)},[])}function Ca(b){return b instanceof Node?b.parentNode?b.cloneNode(!0):b:document.createTextNode(null==b?"":b)}function Da(b){return b.reduce(function(a,b){return a.concat(Array.isArray(b)?Da(b):b)},[])}function Ta(b){return b.templateVersion&&b.templateVersion===qa.V2?Ua(ra,b,"")[0].outerHTML:
Va(ra,b,"")[0].outerHTML}function Wa(b){return Xa(ra,b,"")[0].outerHTML}var V={d:function(b,a){for(var p in a)V.o(a,p)&&!V.o(b,p)&&Object.defineProperty(b,p,{enumerable:!0,get:a[p]})},o:function(b,a){return Object.prototype.hasOwnProperty.call(b,a)},r:function(b){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(b,Symbol.toStringTag,{value:"Module"});Object.defineProperty(b,"__esModule",{value:!0})}},sa={};V.r(sa);V.d(sa,{getDesktopContent:function(){return Wa},getMobileContent:function(){return Ta}});
var Ya=new RegExp(/\d+/g),Ma=new RegExp(/(?:m\.media-amazon\.com\/|images-(?:na|eu|fe)\.ssl-images-amazon\.com\/)(.*?)(?:\.(_(?:.*)?_)\.*)?\.(jpg|jpeg)(\?.*)?/i),la=["SX","SY","SL","SF","SR"],La=function(){for(var b=0,a=0,p=arguments.length;a<p;a++)b+=arguments[a].length;b=Array(b);var m=0;for(a=0;a<p;a++)for(var h=arguments[a],e=0,c=h.length;e<c;e++,m++)b[m]=h[e];return b}(la,"AC RI FMjpg FMjpeg FMwebp TTH TTD TTW CB".split(" ")),ta={avif:{dpi1:58,dpi15:58,dpi2:58},webp:{dpi1:65,dpi15:65,dpi2:65},
jpg:{dpi1:85,dpi15:80,dpi2:80}},va=function(){function b(){}return b.isOperationsAllowed=function(a){return l(r(a))},b.generateSrcset=function(a,b,m,h,e){var p=r(a);if(!p||!l(p))return a;a=function(a,b,m,h){function e(){for(var a=[],b=0;b<arguments.length;b++)a[b]=arguments[b];p.push.apply(p,a);d.push.apply(d,a);c.push.apply(c,a)}var p=[],d=[],c=[];e(m);a.styleCodeArray.forEach(function(b,m){if(0!==m&&m!==a.styleCodeArray.length-1||""!==b){if(""!==b&&"."!==b){if(la.some(function(a){return b.startsWith(a)}))return m=
function(a){for(var b,d=[];b=Ya.exec(a);)d.push({value:parseInt(b[0]),index:b.index,length:b[0].length});return d}(b),m=(X=h=b,g=h,l=h,m.reverse().forEach(function(a){var b=a.value,d=a.index;a=a.length;var m=Math.min(5E3,Math.round(1.5*b)),h=Math.min(5E3,2*b);X=f(X,d,d+a,(1*b).toString());g=f(g,d,d+a,m.toString());l=f(l,d,d+a,h.toString())}),{x1:X,x15:g,x2:l}),p.push(m.x1),d.push(m.x15),void c.push(m.x2);var h,X,g,l}e(b)}});p.push("QL"+ta[b].dpi1);d.push("QL"+ta[b].dpi15);c.push("QL"+ta[b].dpi2);
("jpeg"===a.extension?"jpg":a.extension)!==b&&e("FM"+b);b=a.sourceUrl.replace(a.styleCodeString,"_"+p.join("_")+"_");m=a.sourceUrl.replace(a.styleCodeString,"_"+d.join("_")+"_");var X=a.sourceUrl.replace(a.styleCodeString,"_"+c.join("_")+"_");return{x1:g(a,b,h),x15:g(a,m,h),x2:g(a,X,h)}}(p,b,"AIweblab"+m+","+h,e);b=[];return b.push(a.x1+" 1x"),a.x15!==a.x1&&b.push(a.x15+" 1.5x"),a.x2!==a.x15&&b.push(a.x2+" 2x"),b.join(", ")},b.generateCacheBuster=function(a,b,m,h){var e=r(a);return e&&l(e)?function(a,
b,m){var h=[b];return a.styleCodeArray.forEach(function(b,m){(0!==m&&m!==a.styleCodeArray.length-1||""!==b)&&h.push(b)}),g(a,a.sourceUrl.replace(a.styleCodeString,"_"+h.join("_")+"_"),m)}(e,"AIweblab"+b+","+m,h):a},b}(),W,Ga={nbsp:" ",amp:"\x26",lt:"\x3c",gt:"\x3e",quot:'"',"#x27":"'","#x60":"`"},ab=[/^([\w-]+(\.))*amazon(.(com|in|fr|de|cn|it|nl|sg|es|tr|ae))$/i,/^([\w-]+(\.))*amazon.com.(au|br|mx)$/i,/^([\w-]+(\.))*amazon.co.(uk|jp)$/i],wa=function(){function b(a){this.context=a;this._getTreatmentRecordTriggerCache=
{};this._isWeblabActiveCache={};this._shouldUseWeblabCache="T1"===this.getTreatmentRecordTriggerNoCache("AUI_TEMPLATE_WEBLAB_CACHE_333406")}return b.prototype.deviceType=function(){return this.context.attributes.device_type||"Desktop"},b.prototype.getTreatmentRecordTriggerNoCache=function(a){return this.context.weblabProvider.getTreatmentRecordTrigger(a)},b.prototype.getTreatmentRecordTrigger=function(a){return this._shouldUseWeblabCache?a in this._getTreatmentRecordTriggerCache?this._getTreatmentRecordTriggerCache[a]:
this._getTreatmentRecordTriggerCache[a]=this.getTreatmentRecordTriggerNoCache(a):this.getTreatmentRecordTriggerNoCache(a)},b.prototype.variant=function(a){if(-1<a.indexOf("\x3d"))throw Error("Found \x3d in variant "+a+"-- should be a :");if(-1<this.context.variants.indexOf(a))return!0;if(-1<a.indexOf(":")){var b=a.substring(0,a.lastIndexOf(":"));a=a.substring(a.lastIndexOf(":"),a.length);return this.context.attributes[b]==a}},b.prototype.isWhiteListedUrl=function(a){var b=function(a){if(a.startsWith("//")||
-1!==a.indexOf("://"))return a.split("/",3)[2].split(":",2)[0]}(a);return!b||ab.some(function(a){return a.test(b)})},b.prototype.isWeblabActive=function(a){return this._shouldUseWeblabCache?a in this._isWeblabActiveCache?this._isWeblabActiveCache[a]:this._isWeblabActiveCache[a]=this.context.weblabProvider.isActive(a):this.context.weblabProvider.isActive(a)},b.prototype.weblabClasses=function(){return""},b.prototype.weblabState=function(){return{}},b.prototype.tnr=function(a){var b={};return"T1"==
this.getTreatmentRecordTrigger("AUI_TNR_V2_180836")&&a.forEach(function(a){b["data-ux-"+a]=""}),this.normalizeTable(b)},b.prototype.decToInt=function(a){return a=+a,isFinite(a)?a-a%1||(0>a?-0:0===a?a:0):a},b.prototype.join=function(a,b){return b.join(a)},b.prototype.trim=function(a){return a.trim()},b.prototype.emptyTable=function(){return{}},b.prototype.tableOf=function(a,b){var m={};return m[a]=b,m},b.prototype.parseAttrs=function(a){for(var b={},m=/([:_A-Za-z][-:_.A-Za-z0-9]*)\s*(?:=\s*(?:"((?:[^"\\]|\\.)*)"|'((?:[^'\\]|\\.)*)'|([^ "'`=<>]+)))?/g,
h=m.exec(a);null!=h;)h=h.filter(function(a){return void 0!==a}),b[h[1]]=h[2]||"",h=m.exec(a);return this.normalizeTable(b)},b.prototype.listLength=function(a){return a.length},b.prototype.discard=function(){return""},b.prototype.normalizeTable=function(a){return Object.keys(a).sort().reduce(function(b,m){return b[m]=a[m],b},{})},b.prototype.convertCarouselOptions=function(a){var b="ajax fetch_delay url id_list id_list_param_name animating animation_speed auto_adjust_height circular currentGutter firstVisibleItem first_item_flush_left height_animation_speed hide_off_screen loading maintain_state maxHeight minimum_gutter_width pageNumber pageSize px set_size show_partial_next single_page_align totalPages wrap_easing".split(" "),
m={},h;for(h in a){var e=h.replace(/[\w]([A-Z])/g,function(a){return a[0]+"_"+a[1]}).toLowerCase(),c=a[h];c=Array.isArray(c)||"object"!=("undefined"===typeof c?"undefined":ka(c))?c:this.convertCarouselOptions(c);0<=b.indexOf(e)?m[e]=c:m[h]=c}return m},b.prototype.encodeAttrs=function(a){return Object.keys(a).reduce(function(b,m){return"string"==typeof a[m]?b[m]=a[m]:void 0===a[m]||null===a[m]?b[m]="":b[m]=JSON.stringify(a[m]),b},{})},b.prototype.unescapeHtml=function(a){return a.replace(/&([#a-z0-9]+);/gi,
function(a,b){return Ga[b]?Ga[b]:(b=b.match(/^#x([\da-f]+)$/i))?String.fromCharCode(parseInt(b[1],16)):a})},b.prototype.formatDecimal=function(a){return(Math.round(100*a)/100).toString()},b.prototype.needAssetAfter=function(a,b){throw Error("InjectAuiAssets is an unsupported tag in Javascript targets");},b.prototype.isAmazonImageCompatible=function(a){return va.isOperationsAllowed(a.trim())},b.prototype.getSrcset=function(a,b,m,h,e){return va.generateSrcset(a.trim(),b,m,h,e)},b.prototype.getCacheBuster=
function(a,b,m,h){return va.generateCacheBuster(a.trim(),b,m,h)},b}(),bb=(W=function(b,a){return W=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var h in b)b.hasOwnProperty(h)&&(a[h]=b[h])},W(b,a)},function(b,a){function e(){this.constructor=b}W(b,a);b.prototype=null===a?Object.create(a):(e.prototype=a.prototype,new e)}),M=function(){return M=Object.assign||function(b){for(var a,e=1,m=arguments.length;e<m;e++)for(var h in a=arguments[e])Object.prototype.hasOwnProperty.call(a,
h)&&(b[h]=a[h]);return b},M.apply(this,arguments)},Z=function(b){function a(a){return b.call(this,a)||this}return bb(a,b),a.prototype.isTableEmpty=function(a){return 0===Object.keys(a).length},a.prototype.tableMerge=function(a,b){return M(M({},a),b)},a.prototype.range=function(a,b){b=Math.abs(b-a)+1;var e=this.decToInt(a);return Array.from({length:this.decToInt(b)},function(a,b){return e+b})},a}(wa),J={Button:function(b,a,c){var m,h,f,p,g,l,n,r,t,ea,d=new Z(b.context||{}),G=void 0!==a.aria&&null!==
a.aria?a.aria:{},fa=void 0!==a.buttonModifier&&null!==a.buttonModifier?a.buttonModifier:"Unspecified",Ea=void 0!==a.buttonPosition&&null!==a.buttonPosition?a.buttonPosition:"Unspecified",ua=void 0!==a.buttonSize&&null!==a.buttonSize?a.buttonSize:"Base",k=void 0!==a.buttonType&&null!==a.buttonType?a.buttonType:"Unspecified",F=void 0!==a.cssClass&&null!==a.cssClass?a.cssClass:"",$a=void 0!==a.data&&null!==a.data?a.data:{},B=void 0!==a.formAction&&null!==a.formAction?a.formAction:"",Fa=void 0!==a.gridUnits&&
null!==a.gridUnits?a.gridUnits:0,H=void 0!==a.hideIcon&&null!==a.hideIcon&&a.hideIcon,C=void 0!==a.htmlButtonType&&null!==a.htmlButtonType?a.htmlButtonType:"Submit",Y=void 0!==a.htmlTitle&&null!==a.htmlTitle?a.htmlTitle:"",E=void 0!==a.id&&null!==a.id?a.id:"",S=void 0!==a.isInButtonGroup&&null!==a.isInButtonGroup&&a.isInButtonGroup,Q=void 0!==a.name&&null!==a.name?a.name:"",D=void 0!==a.nativeCssClass&&null!==a.nativeCssClass?a.nativeCssClass:"",T=void 0!==a.nativeId&&null!==a.nativeId?a.nativeId:
"",J=void 0!==a.position&&null!==a.position?a.position:"Unspecified",R=void 0!==a.rel&&null!==a.rel?a.rel:"",Ha=void 0!==a.spacing&&null!==a.spacing?a.spacing:"Unspecified",P=void 0!==a.spacingTop&&null!==a.spacingTop?a.spacingTop:"Unspecified",U=void 0!==a.status&&null!==a.status?a.status:"Unspecified",aa=void 0!==a.tabindex&&null!==a.tabindex?a.tabindex:0,O=void 0!==a.target&&null!==a.target?a.target:"",ba=void 0!==a.textAlign&&null!==a.textAlign?a.textAlign:"Unspecified",I=void 0!==a.tooltip&&
null!==a.tooltip?a.tooltip:"",N=void 0!==a.tooltipPosition&&null!==a.tooltipPosition?a.tooltipPosition:"TriggerTop",V=void 0!==a.unsafeUrl&&null!==a.unsafeUrl?a.unsafeUrl:"",W=void 0!==a.url&&null!==a.url?a.url:"",M=void 0!==a.value&&null!==a.value?a.value:"",da=void 0!==a.widthNamed&&null!==a.widthNamed?a.widthNamed:"Unspecified";return b.root("aui","Button",[[[(m=d.normalizeTable(d.encodeAttrs(d.tableMerge(L(a,"data"),$a))),[(h=d.normalizeTable(d.tableMerge(L(a,"aria"),G)),[b.createElement("span",
(ea={},z(ea,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),""!==E&&(ea.id=E),ea.class=K(["a-button","Unspecified"!==U?"a-button-"+e(U):"","Unspecified"!==fa?"a-button-"+x(fa):"","Unspecified"!==J?"a-button-group"+y(J):"","Unspecified"!==Ha?"a-spacing-"+w(Ha):"","Unspecified"!==P?"a-spacing-top-"+A(P):"",0!==Fa?"a-button-span"+
Fa:"","Unspecified"!==Ea?"a-"+ha(Ea):"","Sns"===k||"Cart"===k?" a-button-primary":"BuyNow"===k?" a-button-oneclick":"OneClickPreorder"===k||"BuyNowPreorder"===k?" a-button-preorder a-button-preorder-secondary":"ToggleUnavailable"===k?" a-button-toggle a-button-unavailable":"Unspecified"===k?"a-button-base":"a-button-"+ca(k),("Small"===ua?" a-button-small":"")+("Base"===da?" a-button-width-normal":""),"Sns"===k||"Cart"===k||"OneClick"===k||"BuyNow"===k||"Preorder"===k||"OneClickPreorder"===k||"BuyNowPreorder"===
k?" a-button-icon":"",""!==F?""+F:""]),ea),b.createElement("span",(t={},z(t,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),t.class="a-button-inner",t),H||"Small"===ua||"Sns"!==k&&"Cart"!==k&&"OneClick"!==k&&"BuyNow"!==k&&"Preorder"!==k&&"OneClickPreorder"!==k&&"BuyNowPreorder"!==k?void 0:b.createElement("i",(r={},z(r,
"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),r.class=K(["a-icon","OneClick"===k?"a-icon-1click":"Preorder"===k?"a-icon-cart":"OneClickPreorder"===k?"a-icon-1click":"BuyNowPreorder"===k?"a-icon-buynow":"a-icon-"+ca(k)]),r)),"Small"!==ua&&"Supplemental"===fa||"Dropdown"===fa?b.createElement("i",(n={},z(n,"",d.normalizeTable("T1"===
d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),n.class=K(["a-icon","a-icon-"+x(fa)]),n)):void 0,""!==W||""!==V?b.createElement("a",(l={},z(l,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
d.emptyTable())),""!==T&&(l.id=T),0!==aa&&(l.tabindex=""+aa),""!==W?l.href=d.unescapeHtml(W):""!==V&&(l.href=d.unescapeHtml(V)),"Disabled"===U&&(l["aria-disabled"]="true"),""!==Q&&(l.name=Q),""===Y&&""===I||(l.title=""!==I?I:Y),""!==O&&(l.target=O),z(l,"",""!==d.trim(d.join(" ",[R,""===O||d.variant("marketplace:cn")||d.variant("marketplace:in")||d.variant("marketplace:jp")?"":"noopener"]))?d.tableOf("rel",d.trim(d.join(" ",[R,""===O||d.variant("marketplace:cn")||d.variant("marketplace:in")||d.variant("marketplace:jp")?
"":"noopener"]))):d.emptyTable()),S&&(l.role="radio",l["aria-checked"]="Selected"===U?"true":"false"),z(l,"data-",m),z(l,"aria-",h),l.class=K(["a-button-text","Unspecified"!==ba?"a-text-"+u(ba):"",""!==I?"a-declarative":"",""!==D?""+D:""]),""!==I&&z(l,"",d.normalizeTable(d.tableMerge("C"===d.getTreatmentRecordTrigger("AUI_KILLSWITCH_CSA_LOGGER_372963")?d.tableMerge(d.tableMerge(d.tableOf("data-csa-c-type","widget"),d.tableOf("data-csa-c-func-deps","aui-da-a-tooltip")),d.tableOf("data-csa-interaction-events",
"click")):d.emptyTable(),d.tableMerge(d.tableMerge(d.tableOf("data-action","a-tooltip"),d.tableOf("data-a-tooltip",'{"position":"'+v(N)+'","content":"'+I+'","allowLinkDefault": true}')),d.tnr("click mouseenter mouseleave focus focusin blur focusout".split(" ")))))),l),c):"Submit"===C?[b.createElement("input",(g={},z(g,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
d.emptyTable())),""!==T&&(g.id=T),0!==aa&&(g.tabindex=""+aa),""!==Q&&(g.name=Q),""===Y&&""===I||(g.title=""!==I?I:Y),""!==O&&(g.target=O),z(g,"",""!==d.trim(d.join(" ",[R,""===O||d.variant("marketplace:cn")||d.variant("marketplace:in")||d.variant("marketplace:jp")?"":"noopener"]))?d.tableOf("rel",d.trim(d.join(" ",[R,""===O||d.variant("marketplace:cn")||d.variant("marketplace:in")||d.variant("marketplace:jp")?"":"noopener"]))):d.emptyTable()),S&&(g.role="radio",g["aria-checked"]="Selected"===U?"true":
"false"),z(g,"data-",m),z(g,"aria-",h),"Disabled"===U&&(g.disabled="disabled"),g.class=K(["a-button-input",""!==I?"a-declarative":"",""!==D?""+D:""]),g.type=q(C),null!==a.formId&&void 0!==a.formId&&(g.form=a.formId),""!==B&&(g.formaction=d.unescapeHtml(B)),""!==M&&(g.value=M),""!==I&&z(g,"",d.normalizeTable(d.tableMerge("C"===d.getTreatmentRecordTrigger("AUI_KILLSWITCH_CSA_LOGGER_372963")?d.tableMerge(d.tableMerge(d.tableOf("data-csa-c-type","widget"),d.tableOf("data-csa-c-func-deps","aui-da-a-tooltip")),
d.tableOf("data-csa-interaction-events","click")):d.emptyTable(),d.tableMerge(d.tableMerge(d.tableOf("data-action","a-tooltip"),d.tableOf("data-a-tooltip",'{"position":"'+v(N)+'","content":"'+I+'","allowLinkDefault": true}')),d.tnr("click mouseenter mouseleave focus focusin blur focusout".split(" ")))))),""===E||null!==h.label&&void 0!==h.label||(g["aria-labelledby"]=E+"-announce"),g)),b.createElement("span",(p={},z(p,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),""!==E&&(p.id=E+"-announce"),p.class=K(["a-button-text","Unspecified"!==ba?"a-text-"+u(ba):""]),p["aria-hidden"]="true",p),c)]:b.createElement("button",(f={},z(f,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
d.emptyTable())),""!==T&&(f.id=T),""!==E&&""===T&&(f.id=E+"-announce"),0!==aa&&(f.tabindex=""+aa),""!==Q&&(f.name=Q),""===Y&&""===I||(f.title=""!==I?I:Y),""!==O&&(f.target=O),z(f,"",""!==d.trim(d.join(" ",[R,""===O||d.variant("marketplace:cn")||d.variant("marketplace:in")||d.variant("marketplace:jp")?"":"noopener"]))?d.tableOf("rel",d.trim(d.join(" ",[R,""===O||d.variant("marketplace:cn")||d.variant("marketplace:in")||d.variant("marketplace:jp")?"":"noopener"]))):d.emptyTable()),S&&(f.role="radio",
f["aria-checked"]="Selected"===U?"true":"false"),z(f,"data-",m),z(f,"aria-",h),"Disabled"===U&&(f.disabled="disabled"),f.class=K(["a-button-text","Unspecified"!==ba?"a-text-"+u(ba):"",""!==I?"a-declarative":"",""!==D?""+D:""]),f.type=q(C),null!==a.formId&&void 0!==a.formId&&(f.form=a.formId),""!==B&&(f.formaction=d.unescapeHtml(B)),""!==M&&(f.value=M),""!==I&&z(f,"",d.normalizeTable(d.tableMerge("C"===d.getTreatmentRecordTrigger("AUI_KILLSWITCH_CSA_LOGGER_372963")?d.tableMerge(d.tableMerge(d.tableOf("data-csa-c-type",
"widget"),d.tableOf("data-csa-c-func-deps","aui-da-a-tooltip")),d.tableOf("data-csa-interaction-events","click")):d.emptyTable(),d.tableMerge(d.tableMerge(d.tableOf("data-action","a-tooltip"),d.tableOf("data-a-tooltip",'{"position":"'+v(N)+'","content":"'+I+'","allowLinkDefault": true}')),d.tnr("click mouseenter mouseleave focus focusin blur focusout".split(" ")))))),f),c)))])])]]])},Text:function(b,a,e){var m,h,c,f=new Z(b.context||{}),g=void 0!==a.aria&&null!==a.aria?a.aria:{},p=void 0!==a.cssClass&&
null!==a.cssClass?a.cssClass:"",l=void 0!==a.data&&null!==a.data?a.data:{},n=void 0!==a.id&&null!==a.id?a.id:"",q=void 0!==a.role&&null!==a.role?a.role:"Unspecified",r=void 0!==a.textBold&&null!==a.textBold&&a.textBold,d=void 0!==a.textCapitalize&&null!==a.textCapitalize&&a.textCapitalize,x=void 0!==a.textColor&&null!==a.textColor?a.textColor:"Unspecified",u=void 0!==a.textDirection&&null!==a.textDirection?a.textDirection:"Unspecified",t=void 0!==a.textEmphasis&&null!==a.textEmphasis&&a.textEmphasis,
v=void 0!==a.textNormal&&null!==a.textNormal&&a.textNormal,k=void 0!==a.textNowrap&&null!==a.textNowrap&&a.textNowrap,y=void 0!==a.textPosition&&null!==a.textPosition?a.textPosition:"Unspecified",w=void 0!==a.textQuote&&null!==a.textQuote&&a.textQuote,B=void 0!==a.textSize&&null!==a.textSize?a.textSize:"Unspecified",A=void 0!==a.textStrikethrough&&null!==a.textStrikethrough&&a.textStrikethrough;return b.root("aui","Text",[[[b.createElement("span",(c={},na(c,"",f.normalizeTable("T1"===f.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
f.tableMerge(f.tableOf("data-a-version","3.25.5"),f.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):f.emptyTable())),""!==n&&(c.id=n),na(c,"data-",f.normalizeTable(f.encodeAttrs(f.tableMerge(Aa(a,"data"),l)))),na(c,"aria-",f.normalizeTable(f.tableMerge(Aa(a,"aria"),g))),c.class=(m=["Unspecified"!==B?"a-size-"+Oa(B):"","Unspecified"!==x?"a-color-"+Pa(x):"","Unspecified"!==y?"a-"+Qa(y):"",p,f.trim(f.join("",[r?"a-text-bold":"",d?" a-text-caps":"",t?" a-text-italic":"",k?
" a-nowrap":"",w?" a-text-quote":"",A?" a-text-strike":"",v?" a-text-normal":""]))],0<(h=m.join(" ").split(" ").filter(Ra).join(" ")).length?h:void 0),"Unspecified"!==q&&(c.role=function(a){switch(a){case "Unspecified":return"unspecified";case "Alert":return"alert";case "AlertDialog":return"alertdialog";case "Application":return"application";case "Article":return"article";case "Banner":return"banner";case "Button":return"button";case "Checkbox":return"checkbox";case "ColumnHeader":return"columnheader";
case "ComboBox":return"combobox";case "Complementary":return"complementary";case "ContentInfo":return"contentinfo";case "Definition":return"definition";case "Dialog":return"dialog";case "Directory":return"directory";case "Document":return"document";case "Form":return"form";case "Grid":return"grid";case "GridCell":return"gridcell";case "Group":return"group";case "Heading":return"heading";case "Img":return"img";case "Link":return"link";case "List":return"list";case "ListBox":return"listbox";case "ListItem":return"listitem";
case "Log":return"log";case "Main":return"main";case "Marquee":return"marquee";case "Math":return"math";case "Menu":return"menu";case "MenuBar":return"menubar";case "MenuItem":return"menuitem";case "MenuItemCheckbox":return"menuitemcheckbox";case "MenuItemRadio":return"menuitemradio";case "Navigation":return"navigation";case "Note":return"note";case "Option":return"option";case "Presentation":return"presentation";case "ProgressBar":return"progressbar";case "Radio":return"radio";case "RadioGroup":return"radiogroup";
case "Region":return"region";case "Row":return"row";case "RowGroup":return"rowgroup";case "RowHeader":return"rowheader";case "Scrollbar":return"scrollbar";case "Search":return"search";case "Separator":return"separator";case "Slider":return"slider";case "SpinButton":return"spinbutton";case "Status":return"status";case "Tab":return"tab";case "TabList":return"tablist";case "TabPanel":return"tabpanel";case "TextBox":return"textbox";case "Timer":return"timer";case "Toolbar":return"toolbar";case "Tooltip":return"tooltip";
case "Tree":return"tree";case "TreeGrid":return"treegrid";case "TreeItem":return"treeitem";default:return a}}(q)),"Unspecified"!==u&&(c.dir=function(a){switch(a){case "Unspecified":return"unspecified";case "Ltr":return"ltr";case "Rtl":return"rtl";case "Auto":return"auto";default:return a}}(u)),c),e)]]])},DeclarativeAction:function(b,a,e){var c,h=new Z(b.context||{}),f=void 0!==a.actionName&&null!==a.actionName?a.actionName:"",g=void 0!==a.actionParams&&null!==a.actionParams?a.actionParams:{},l=void 0!==
a.extra&&null!==a.extra?a.extra:"";a=void 0!==a.id&&null!==a.id?a.id:"";return b.root("aui","DeclarativeAction",[[[b.createElement("span",(c={},oa(c,"",h.normalizeTable("T1"===h.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?h.tableMerge(h.tableOf("data-a-version","3.25.5"),h.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):h.emptyTable())),c.class="a-declarative",c["data-action"]=f,"C"===h.getTreatmentRecordTrigger("AUI_KILLSWITCH_CSA_LOGGER_372963")&&(c["data-csa-c-type"]=
"widget",c["data-csa-c-func-deps"]="aui-da-"+f),oa(c,"data-",h.tableOf(f,JSON.stringify(g).replace(/</g,"\\u003c"))),""!==a&&(c.id=a),""!==l&&oa(c,"",h.parseAttrs(l)),c),e)]]])},Price:function(b,a,e){var c,h,f,g,l,p,n,q,r,x,d,u,v,y,w,k=new Z(b.context||{});e=void 0!==a.altText&&null!==a.altText?a.altText:"";var A=void 0!==a.cssClass&&null!==a.cssClass?a.cssClass:"",z=void 0!==a.currencySymbol&&null!==a.currencySymbol?a.currencySymbol:"",B=void 0!==a.currencySymbolPosition&&null!==a.currencySymbolPosition?
a.currencySymbolPosition:"Left",D=void 0!==a.decimalSeparator&&null!==a.decimalSeparator?a.decimalSeparator:"",H=void 0!==a.fractionalValue&&null!==a.fractionalValue?a.fractionalValue:"",C=void 0!==a.id&&null!==a.id?a.id:"",F=void 0!==a.priceColor&&null!==a.priceColor?a.priceColor:"Unspecified",E=void 0!==a.priceSize&&null!==a.priceSize?a.priceSize:"Large",S=void 0!==a.strikethrough&&null!==a.strikethrough&&a.strikethrough;a=void 0!==a.wholeValue&&null!==a.wholeValue?a.wholeValue:"";return b.root("aui",
"Price",[[[(c=k.variant("rtl:true"),[["Mini"===E||"Small"===E||"Base"===E?b.createElement("span",(w={},G(w,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),""!==C&&(w.id=C),w.class=N(["a-price","a-text-price",A]),"Base"===E&&(w["data-a-size"]="b"),"Small"===E&&(w["data-a-size"]="s"),"Mini"===E&&(w["data-a-size"]="mini"),
S&&(w["data-a-strike"]="true"),"Unspecified"!==F&&(w["data-a-color"]=Ba(F)),w),b.createElement("span",(y={},G(y,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),y.class="a-offscreen",y),""!==e?t(0,{content:e}):c?["Left"===B?b.createElement("span",(v={},G(v,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),v.dir="rtl",v),t(0,{content:z})):void 0,"‎",t(0,{content:a}),""!==H?[t(0,{content:D}),t(0,{content:H})]:void 0,"Right"===B?b.createElement("span",(u={},G(u,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
k.emptyTable())),u.dir="rtl",u),t(0,{content:z})):void 0,"‎"]:["Left"===B?t(0,{content:z}):void 0,t(0,{content:a}),""!==H?[t(0,{content:D}),t(0,{content:H})]:void 0,"Right"===B?t(0,{content:z}):void 0]),b.createElement("span",(d={},G(d,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),d["aria-hidden"]="true",c&&(d.dir=
"ltr"),d),c?["Left"===B?b.createElement("span",(x={},G(x,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),x.dir="rtl",x),t(0,{content:z})):void 0,"‎",t(0,{content:a}),""!==H?[t(0,{content:D}),t(0,{content:H})]:void 0,"Right"===B?b.createElement("span",(r={},G(r,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),r.dir="rtl",r),t(0,{content:z})):void 0,"‎"]:["Left"===B?t(0,{content:z}):void 0,t(0,{content:a}),""!==H?[t(0,{content:D}),t(0,{content:H})]:void 0,"Right"===B?t(0,{content:z}):void 0])):b.createElement("span",(q={},G(q,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),
k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),""!==C&&(q.id=C),q.class=N(["a-price",A]),"ExtraExtraLarge"===E&&(q["data-a-size"]="xxl"),"ExtraLarge"===E&&(q["data-a-size"]="xl"),"Large"===E&&(q["data-a-size"]="l"),"Medium"===E&&(q["data-a-size"]="m"),"BasePlus"===E&&(q["data-a-size"]="base_plus"),"MediumPlus"===E&&(q["data-a-size"]="medium_plus"),q["data-a-color"]=""+("Unspecified"===F?"base":Ba(F)),q),b.createElement("span",(n={},G(n,"",k.normalizeTable("T1"===
k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),n.class="a-offscreen",n),""!==e?t(0,{content:e}):c?["Left"===B?b.createElement("span",(p={},G(p,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
k.emptyTable())),p.dir="rtl",p),t(0,{content:z})):void 0,"‎",t(0,{content:a}),""!==H?[t(0,{content:D}),t(0,{content:H})]:void 0,"Right"===B?b.createElement("span",(l={},G(l,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),l.dir="rtl",l),t(0,{content:z})):void 0,"‎"]:["Left"===B?t(0,{content:z}):void 0,t(0,{content:a}),
""!==H?[t(0,{content:D}),t(0,{content:H})]:void 0,"Right"===B?t(0,{content:z}):void 0]),b.createElement("span",(g={},G(g,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),g["aria-hidden"]="true",c&&(g.dir="ltr"),g),"Left"===B?[[[b.createElement("span",function(){var a={};return G(a,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),a.class=N(["a-price-symbol"]),c&&(a.dir="rtl"),a}(),t(0,{content:z})),c?"‎":void 0]]]:void 0,b.createElement("span",(f={},G(f,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),
f.class="a-price-whole",f),t(0,{content:a}),""!==H?[[[b.createElement("span",function(){var a={};return G(a,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),a.class=N(["a-price-decimal"]),c&&(a.dir="ltr"),a}(),t(0,{content:D})),c?"‎":void 0]]]:void 0),""!==H?b.createElement("span",(h={},G(h,"",k.normalizeTable("T1"===
k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):k.emptyTable())),h.class="a-price-fraction",h),t(0,{content:H})):void 0,"Right"===B?[[[b.createElement("span",function(){var a={};return G(a,"",k.normalizeTable("T1"===k.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?k.tableMerge(k.tableOf("data-a-version","3.25.5"),k.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
k.emptyTable())),a.class=N(["a-price-symbol"]),c&&(a.dir="rtl"),a}(),t(0,{content:z})),c?"‎":void 0]]]:void 0)),c?"‏":void 0]])]]])},Dropdown:function(b,a,e){var c,h,f,g,l,p,n,q,r,x,d=new Z(b.context||{}),u=void 0!==a.actionId&&null!==a.actionId?a.actionId:"",v=void 0!==a.aria&&null!==a.aria?a.aria:{},y=void 0!==a.ariaLabel&&null!==a.ariaLabel?a.ariaLabel:"",z=void 0!==a.buttonSize&&null!==a.buttonSize?a.buttonSize:"Base",k=void 0!==a.cssClass&&null!==a.cssClass?a.cssClass:"",D=void 0!==a.data&&null!==
a.data?a.data:{},C=void 0!==a.dropdownMaxHeight&&null!==a.dropdownMaxHeight?a.dropdownMaxHeight:"",B=void 0!==a.gridUnits&&null!==a.gridUnits?a.gridUnits:0,G=void 0!==a.hasFooter&&null!==a.hasFooter&&a.hasFooter,H=void 0!==a.hasImages&&null!==a.hasImages&&a.hasImages,S=void 0!==a.id&&null!==a.id?a.id:"",J=void 0!==a.labelText&&null!==a.labelText?a.labelText:"",E=void 0!==a.name&&null!==a.name?a.name:"",K=void 0!==a.nativeCssClass&&null!==a.nativeCssClass?a.nativeCssClass:"",Q=void 0!==a.nativeId&&
null!==a.nativeId?a.nativeId:"",N=void 0!==a.optionPrompt&&null!==a.optionPrompt?a.optionPrompt:"",T=void 0!==a.selectedOption&&null!==a.selectedOption?a.selectedOption:"",M=void 0!==a.spacing&&null!==a.spacing?a.spacing:"Unspecified",R=void 0!==a.spacingTop&&null!==a.spacingTop?a.spacingTop:"Unspecified",L=void 0!==a.status&&null!==a.status?a.status:"Unspecified",P=void 0!==a.touchHeader&&null!==a.touchHeader?a.touchHeader:"",U=void 0!==a.widthNamed&&null!==a.widthNamed?a.widthNamed:"Unspecified";
return b.root("aui","Dropdown",[[[b.createElement("span",(x={},F(x,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),x.class="a-dropdown-container",x),""!==J?b.createElement("label",(r={},F(r,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),
d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),""!==Q&&(r.for=Q),r.class=ia(["a-native-dropdown",K]),r),t(0,{content:J})):void 0,b.createElement("select",(q={},F(q,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),q.name=E,q.autocomplete="off",q.role="combobox",H&&(q["data-a-has-images"]=
H?"true":"false"),""!==K&&(q["data-a-native-class"]=K),""!==P&&(q["data-a-touch-header"]=P),""!==C&&(q["data-a-max-height"]=C),""!==u&&(q["data-a-action-id"]=u),G&&(q["data-a-has-footer"]=G?"true":"false"),""!==Q&&(q.id=Q),q.tabindex="0",q["data-action"]="a-dropdown-select",F(q,"aria-",d.normalizeTable(d.tableMerge(ja(a,"aria"),v))),""!==y&&(q["aria-label"]=y),q.class=ia(["a-native-dropdown",0!==B?"a-button-span"+B:"","Unspecified"!==M?"a-spacing-"+w(M):"","Unspecified"!==R?"a-spacing-top-"+A(R):
"","a-declarative",K]),"Disabled"===L&&(q.disabled="disabled"),q),""!==N?b.createElement("option",(n={},F(n,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),n.class="a-prompt",n.value="",n),t(0,{content:N})):void 0,e),b.createElement("span",(p={},F(p,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),p.tabindex="-1",""!==S&&(p.id=S),F(p,"data-",d.normalizeTable(d.encodeAttrs(d.tableMerge(ja(a,"data"),D)))),""!==k&&(p["data-a-class"]=k),p.class=ia(["a-button","a-button-dropdown",("Small"===z?" a-button-small":"")+("Base"===U?" a-button-width-normal":""),"Unspecified"!==M?"a-spacing-"+w(M):"","Unspecified"!==R?"a-spacing-top-"+A(R):"",0!==B?"a-button-span"+
B:"",k,"Disabled"===L?"a-button-disabled":"Error"===L?"a-button-error":""]),p["aria-hidden"]="true","Disabled"===L&&(p["aria-disabled"]="true"),p),b.createElement("span",(l={},F(l,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),l.class="a-button-inner",l),b.createElement("span",(g={},F(g,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?
d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),g.class="a-button-text a-declarative",F(g,"data-",d.normalizeTable(d.encodeAttrs(d.tableMerge(ja(a,"data"),d.tableMerge(d.emptyTable(),"C"===d.getTreatmentRecordTrigger("AUI_KILLSWITCH_CSA_LOGGER_372963")?d.tableMerge(d.tableMerge(d.tableOf("csa-c-type","widget"),d.tableOf("csa-c-func-deps","aui-da-a-dropdown-button")),d.tableOf("csa-interaction-events",
"click")):d.emptyTable()))))),g["data-action"]="a-dropdown-button",g["aria-hidden"]="true","Disabled"!==L&&F(g,"",d.tnr(["click","keydown"])),g),""!==J?b.createElement("span",(f={},F(f,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),f.class="a-dropdown-label",f),t(0,{content:J})):void 0,b.createElement("span",(h={},F(h,
"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):d.emptyTable())),h.class="a-dropdown-prompt",h),t(0,{content:""!==T?T:N}))),b.createElement("i",(c={},F(c,"",d.normalizeTable("T1"===d.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?d.tableMerge(d.tableOf("data-a-version","3.25.5"),d.tableOf("data-a-templates-pcv","2aa3df790132a40705a7b35daf432dc0650cbd39")):
d.emptyTable())),c.class="a-icon a-icon-dropdown",c)))))]]])},DropdownOption:function(b,a,c){var e,h,f=new Z(b.context||{}),g=void 0!==a.aria&&null!==a.aria?a.aria:{},l=void 0!==a.cssClass&&null!==a.cssClass?a.cssClass:"",p=void 0!==a.data&&null!==a.data?a.data:{},q=void 0!==a.htmlContent&&null!==a.htmlContent?a.htmlContent:"",n=void 0!==a.id&&null!==a.id?a.id:"",r=void 0!==a.imageSource&&null!==a.imageSource?a.imageSource:"",x=void 0!==a.labelText&&null!==a.labelText?a.labelText:"",d=void 0!==a.nativeCssClass&&
null!==a.nativeCssClass?a.nativeCssClass:"",u=void 0!==a.nativeId&&null!==a.nativeId?a.nativeId:"",v=void 0!==a.optionFaded&&null!==a.optionFaded&&a.optionFaded,t=void 0!==a.selected&&null!==a.selected&&a.selected,w=void 0!==a.value&&null!==a.value?a.value:"";return b.root("aui","DropdownOption",[[[b.createElement("option",(h={},ma(h,"",f.normalizeTable("T1"===f.getTreatmentRecordTrigger("AUI_VERSION_INSTRUMENTATION")?f.tableMerge(f.tableOf("data-a-version","3.25.5"),f.tableOf("data-a-templates-pcv",
"2aa3df790132a40705a7b35daf432dc0650cbd39")):f.emptyTable())),ma(h,"data-",f.normalizeTable(f.encodeAttrs(f.tableMerge(za(a,"data"),p)))),ma(h,"aria-",f.normalizeTable(f.tableMerge(za(a,"aria"),g))),h.value=w,""!==d&&(h.class=0<(e=[d].join(" ").split(" ").filter(Na).join(" ")).length?e:void 0),(v||""!==l)&&(h["data-a-css-class"]=f.trim(f.join(" ",[l,v?"a-color-tertiary":""]))),""!==u&&(h.id=u),""!==n&&(h["data-a-id"]=n),""!==q&&(h["data-a-html-content"]=q),""!==r&&(h["data-a-image-source"]=r),""!==
x&&(h.label=x),t&&(h.selected=!0),h),c)]]])}},Va=function(b,a,c){c=void 0!==a.selectQuantityText&&null!==a.selectQuantityText?a.selectQuantityText:"";var e=void 0!==a.asinImageUrl&&null!==a.asinImageUrl?a.asinImageUrl:"",h=void 0!==a.pricePerUnitDisplayString&&null!==a.pricePerUnitDisplayString?a.pricePerUnitDisplayString:"",f=void 0!==a.estTotalPriceText&&null!==a.estTotalPriceText?a.estTotalPriceText:"",g=void 0!==a.estTotalWeightText&&null!==a.estTotalWeightText?a.estTotalWeightText:"",l=void 0!==
a.itemWeightUnit&&null!==a.itemWeightUnit?a.itemWeightUnit:"",p=void 0!==a.currencySymbolPosition&&null!==a.currencySymbolPosition?a.currencySymbolPosition:"Left",q=void 0!==a.summaryDisclaimerText&&null!==a.summaryDisclaimerText?a.summaryDisclaimerText:"",n=void 0!==a.summaryAtcButtonText&&null!==a.summaryAtcButtonText?a.summaryAtcButtonText:"",r=void 0!==a.quantitySelectorUnitText&&null!==a.quantitySelectorUnitText?a.quantitySelectorUnitText:"";b.assertNotNull(a,"selectQuantityText asinImageUrl estTotalPriceText itemWeightUnit currencySymbolPosition summaryDisclaimerText summaryAtcButtonText selectorDisplayValues priceSymbol priceDecimalSeparator".split(" "));
var x,d=b.dynamicInstance("aui","Text",J),u=b.dynamicInstance("aui","Price",J),v=b.dynamicInstance("aui","Button",J),t=b.dynamicInstance("aui","DeclarativeAction",J);return b.root("@amzn/portablecta","VariableWeightMobile",[b.createElement("div",{class:"pvw-bs-container"},d(b,{textBold:!0,cssClass:"pvw-bs-heading",id:"pvw-bs-heading-id"},[c]),b.createElement("div",{class:"pvw-bs-content-container"},b.createElement("div",{class:"pvw-asin-image-container"},b.createElement("img",{class:"pvw-asin-image",
src:e})),b.createElement("div",{class:"pvw-scroll-picker-wrapper"},b.createElement("div",{class:"pvw-scroll-picker"},b.createElement("div",{class:"pvw-scroll-picker-mask"}),b.createElement("ul",{class:"pvw-scroll-picker-list",role:"listbox",tabindex:"0","aria-labelledby":"pvw-bs-heading-id"},(x=a.selectorDisplayValues,!x.map&&Java.from?Java.from(x):x).map(function(a){return[b.createElement("li",{class:"pvw-scroll-picker-item",role:"option",tabindex:"-1"},b.createElement("span",{},a))]}),b.createElement("li",
{class:"pvw-scroll-picker-item","aria-hidden":"true"}))),b.createElement("div",{class:"pvw-scroll-picker-overlay"})),b.createElement("div",{class:"pvw-selector-unit-text"},r)),b.createElement("div",{class:"pvw-bs-summary"},b.createElement("div",{class:"pvw-bs-est-wrapper"},b.createElement("div",{},d(b,{textSize:"Small",textBold:!0,cssClass:"aok-block"},[h]),null!==a.estSingleItemWeight&&void 0!==a.estSingleItemWeight?b.createElement("div",{class:"pvw-bs-item-weight-wrapper"},d(b,{textSize:"Small"},
[g]),d(b,{textSize:"Small",cssClass:"pvw-bs-item-weight"},[""+a.estSingleItemWeight]),d(b,{textSize:"Small"},[l])):void 0),b.createElement("div",{class:"pvw-bs-price-wrapper"},d(b,{textColor:"Base",textSize:"Small",cssClass:"aok-block"},[f]),u(b,{currencySymbol:a.priceSymbol,currencySymbolPosition:p,decimalSeparator:a.priceDecimalSeparator,fractionalValue:"00",priceSize:"ExtraExtraLarge"},[]))),d(b,{textSize:"Mini",cssClass:"pvw-bs-summary-disclaimer aok-block"},[q]),t(b,{actionName:"pvw-bs-atc-click"},
[v(b,{buttonType:"Primary",buttonSize:"Base",widthNamed:"Large",htmlButtonType:"Button"},[n])])))])},Ua=function(b,a,c){c=void 0!==a.summaryAtcButtonText&&null!==a.summaryAtcButtonText?a.summaryAtcButtonText:"";var e=void 0!==a.disclaimerText&&null!==a.disclaimerText?a.disclaimerText:"",f=void 0!==a.aboutEstimationText&&null!==a.aboutEstimationText?a.aboutEstimationText:"";b.assertNotNull(a,["summaryAtcButtonText","selectorDisplayValues","disclaimerText","aboutEstimationText"]);var g,l=b.dynamicInstance("aui",
"Text",J),p=b.dynamicInstance("aui","Button",J),q=b.dynamicInstance("aui","DeclarativeAction",J);return b.root("@amzn/portablecta","VariableWeightMobileV2",[b.createElement("div",{class:"pvw-bs-container-v2"},b.createElement("div",{class:"pvw-bs-content-container-v2"},b.createElement("div",{class:"pvw-scroll-picker-wrapper"},b.createElement("div",{class:"pvw-scroll-picker-v2"},b.createElement("ul",{class:"pvw-scroll-picker-list-v2",role:"listbox",tabindex:"0"},(g=a.selectorDisplayValues,!g.map&&Java.from?
Java.from(g):g).map(function(a){return[b.createElement("li",{class:"pvw-scroll-picker-item-v2",role:"option",tabindex:"-1"},b.createElement("span",{},a))]}),b.createElement("li",{class:"pvw-scroll-picker-item-v2"}),b.createElement("li",{class:"pvw-scroll-picker-item-v2"}))),b.createElement("div",{class:"pvw-scroll-picker-overlay-v2"}))),b.createElement("div",{class:"pvw-bs-disclaimer-wrapper"},b.createElement("div",{class:"pvw-bs-disclaimer-container"},l(b,{cssClass:"pvw-about-est-text",textBold:!0},
[f]),l(b,{},[e]))),b.createElement("div",{class:"pvw-atc-button-container"},q(b,{actionName:"pvw-bs-atc-click"},[p(b,{buttonType:"Primary",buttonSize:"Base",widthNamed:"Large",htmlButtonType:"Button"},[c])])))])},Xa=function(b,a,c){b.assertNotNull(a,["asin","selectedOption","dropdownOptions"]);var e,f=b.dynamicInstance("aui","DropdownOption",J);c=b.dynamicInstance("aui","Dropdown",J);return b.root("@amzn/portablecta","VariableWeightDesktop",[b.createElement("div",{class:"pvw-dropdown-container"},
c(b,{cssClass:"pvw-dropdown",name:a.asin,actionId:"pvw-dropdown-"+a.asin,hasFooter:!0,dropdownMaxHeight:"237px",selectedOption:a.selectedOption},[(e=a.dropdownOptions,!e.map&&Java.from?Java.from(e):e).map(function(c){return[f(b,{cssClass:"pvw-dropdown-option",value:c.value,htmlContent:c.displayValue,selected:c.value===a.selectedOption},[c.displayText])]})]))])},cb=0;wa=function(){function b(){xa(this,b);this.context={}}ya(b,[{key:"generateInstanceId",value:function(){return"inst"+cb++}},{key:"root",
value:function(a,b,c){var e=new Set;return pa(c).filter(function(a){return!!a}).map(function(a){a=Ca(a);return e.has(a)?a.cloneNode(!0):(e.add(a),a)})}},{key:"createElement",value:function(a,b){for(var c=document.createElement(a),e=arguments.length,f=Array(2<e?e-2:0),g=2;g<e;g++)f[g-2]=arguments[g];return Object.entries(b).forEach(function(a){a=P(a,2);return c.setAttribute(a[0],a[1])}),pa(f).forEach(function(a){return c.appendChild(Ca(a))}),c}},{key:"assertNotNull",value:function(a,b){var c=!0,e=
!1,f=C;try{for(var g=b[Symbol.iterator](),l;!(c=(l=g.next()).done);c=!0){var q=l.value;if(!a.hasOwnProperty(q)||null==q)throw Error("Required template key is undefined: "+q);}}catch(Za){e=!0,f=Za}finally{try{!c&&g.return&&g.return()}finally{if(e)throw f;}}}},{key:"createComment",value:function(a){return document.createComment(a)}},{key:"createDoctype",value:function(a){return document.implementation.createDocumentType(a,"","")}},{key:"shallowMerge",value:function(a,b){return Object.assign(Object.assign({},
a),b)}},{key:"dynamicInstance",value:function(a,b,c){}},{key:"testCondition",value:function(a){return!1}}]);return b}();var qa;!function(b){b.V1="V1";b.V2="V2"}(qa||(qa={}));var ra=new (function(b){function a(){xa(this,a);var b=Ia(this,(a.__proto__||Object.getPrototypeOf(a)).apply(this,arguments));b;b.context={variants:[],attributes:{},weblabProvider:{getTreatmentRecordTrigger:function(){return"C"},getTreatmentNoTrigger:function(){return"C"},isActive:!1}};return b}Ja(a,b);ya(a,[{key:"createElement",
value:function(a,b){for(var c=document.createElement(a),e=arguments.length,f=Array(2<e?e-2:0),g=2;g<e;g++)f[g-2]=arguments[g];return Object.entries(b).filter(function(a){return void 0!==P(a,2)[1]}).forEach(function(a){a=P(a,2);return c.setAttribute(a[0],a[1])}),Da(f).forEach(function(a){return c.appendChild(function(a){return a instanceof Node?a.parentNode?a.cloneNode(!0):a:document.createTextNode(null==a?"":a)}(a))}),c}},{key:"dynamicInstance",value:function(a,b,c){var e,f=void 0;if("object"==("undefined"===
typeof c?"undefined":ka(c))&&(f=(null===(e=c[b])||void 0===e?void 0:e.default)||c[b]),"function"==typeof c&&(f=c(b)),!f)throw Error("Unable to dynamically import "+a+":"+b);if("function"!=typeof f)throw Error("Expecting "+a+":"+b+" to be a method, but was: "+("undefined"===typeof f?"undefined":ka(f)));return f}}]);return a}(wa));c=sa})();return c})});"use strict";y.when("PVWDuplicationGuard").execute("pvw-pricing-utils-registration",function(c){c.when("pvw-constants").register("pvw-pricing-utils",
function(c){return{calculatePrice:function(c,f,r){c*=f;if(r)return{whole:Math.floor(c),fraction:0};r=Math.round(Math.round(c%1*1E4)/100);return{whole:Math.trunc(c)+Math.floor(r/100),fraction:r%100}},isNonFractionalCurrency:function(c){return"JPY"===c},formatPriceForDisplay:function(f,l,r,g,e){var n=5<arguments.length&&arguments[5]!==C?arguments[5]:c.PRECISION_DEFAULT,v="Left"===g;n=r?f.whole:parseFloat(f.whole+"."+f.fraction).toFixed(n);"."!==e&&e&&(n=n.replace(".",e));return v?""+l+n:""+n+l}}})});
"use strict";P=function(){return function(c,f){if(Array.isArray(c))return c;if(Symbol.iterator in Object(c)){var n=[],l=!0,r=!1,g=C;try{for(var e=c[Symbol.iterator](),u;!(l=(u=e.next()).done)&&(n.push(u.value),!f||n.length!==f);l=!0);}catch(v){r=!0,g=v}finally{try{if(!l&&e["return"])e["return"]()}finally{if(r)throw g;}}return n}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}();y.when("PVWDuplicationGuard").execute("pvw-weight-utils-registration",function(c){c.when("pvw-constants").register("pvw-weight-utils",
function(c){function f(f,n){var g=2<arguments.length&&arguments[2]!==C?arguments[2]:c.PRECISION_DEFAULT,e=3<arguments.length&&arguments[3]!==C?arguments[3]:c.DECIMAL_SEPARATOR,l=P(n===c.UNITS.GRAM_SYMBOL&&1E3<=f?[f/1E3,c.UNITS.KILOGRAM_SYMBOL]:[f,n],2),r=l[0];l=l[1];return(e!==c.DECIMAL_SEPARATOR?r.toFixed(g).replace(c.DECIMAL_SEPARATOR,e):r.toFixed(g))+" "+l}return{calculateEstWeight:function(c,f,g){return g?(f*c).toFixed(2):c.toFixed(2)},getWeightUnitSymbol:function(f){return c.UNITS.UNIT_SYMBOL_MAP[f]||
c.UNITS.POUND_SYMBOL},formatWeightsForDisplay:function(l,n){var g=2<arguments.length&&arguments[2]!==C?arguments[2]:c.PRECISION_DEFAULT,e=3<arguments.length&&arguments[3]!==C?arguments[3]:c.DECIMAL_SEPARATOR;return l.map(function(c){return f(c,n,g,e)})},formatWeight:f}})});"use strict";y.when("PVWDuplicationGuard").execute("pvw-csm-util-registration",function(c){c.register("pvw-csm-util",function(){function c(c){w.ue&&w.ue.count&&c&&w.ue.count(c,(w.ue.count(c)||0)+1)}function n(c,e){return e?c+r.SUCCESS_COUNT:
c+r.FAILED_COUNT}function l(c,e){return e?c+":mobile":c+":desktop"}var r={INITIALIZE:"PortableVariableBottomSheet-Initialize",TRIGGER_ACTION:"PortableVariableBottomSheet-TriggerAction",SHOW_POPUP:"PortableVariableBottomSheet-ShowPopup",SUCCESS_COUNT:"-Success-Count",FAILED_COUNT:"-Failed-Count",HUNDREDTHS:"-Hundredths"};return{incrementTriggerDeclarativeActionCount:function(f,e,u){var g=r.TRIGGER_ACTION;g=n(g,e);g=l(g+":"+f,u);c(g)},incrementShowPopup:function(f,e){f=n(r.SHOW_POPUP,f);f=l(f,e);c(f)},
incrementInitializeCount:function(f,e){f=n(r.INITIALIZE,f);f=l(f,e);c(f)},logLatencyMetric:function(c,e,f){var g="PortableVariableBottomSheet-TimeTo"+r.HUNDREDTHS+c;c=l("PortableVariableBottomSheet-TimeTo"+c,f);g=l(g,f);w.ue&&w.ue.count&&c&&"undefined"!==typeof w.ue_t0&&(e-=w.ue_t0,w.ue.count(c,e),w.ue.count(g,Math.floor(e/10)))}}})});"use strict";y.when("PVWDuplicationGuard").execute("pvw-text-replace-registration",function(c){c.when("pvw-pricing-utils","pvw-weight-utils","pvw-constants","pvw-bs-translations").register("pvw-text-replace",
function(c,n,l,r){function f(e,f){var g=0!==e&&e?e:f.sellingMin;if(f.isItemSoldByCount){e=n.calculateEstWeight(g,f.estimateAverageSize,f.isItemSoldByCount);var q=f.estimateAverageSizeUnitOfMeasureUnit?n.getWeightUnitSymbol(f.estimateAverageSizeUnitOfMeasureUnit):n.getWeightUnitSymbol(f.pricingUnitOfMeasureUnit);return n.formatWeight(Number(e),q,l.PRECISION_DEFAULT,f.decimalSeparator)}e=f.currencySymbol;q=c.isNonFractionalCurrency(f.pricePerUnitMoneyCurrencyCode);g=c.calculatePrice(f.pricePerSingleUnitAmount,
g,q);return c.formatPriceForDisplay(g,e,q,f.currencySymbolPosition||"Left",f.decimalSeparator)}function e(c,e){return"number"!==typeof c||0>c?(console.warn("Invalid quantity provided",c),!1):e?!0:!1}var u='\x3cspan class\x3d"a-text-bold"\x3e{replace}\x3c/span\x3e\x26nbsp\x3cspan\x3e'+r.variableWeightDisclaimer+"\x3c/span\x3e",v='\x3cspan class\x3d"a-text-bold"\x3e{replace}\x3c/span\x3e\x3cbr\x3e\x3cspan\x3e'+r.variableWeightDisclaimer+"\x3c/span\x3e";return{replaceRegulatoryText:function(c,g,n){e(c,
n)?(g=g.closest(l.PVW_CONTAINER).find(l.PVW_REPLACE),g||(console.warn("Unable to find target element for text replacement"),g=null),g?(c=f(c,n),c=r.aboutUpperCase.replace(l.TEMPLATE_REPLACE_STRING.ESTIMATE,c),c=u.replace(l.TEMPLATE_REPLACE_STRING.REPLACE,c),g={targetElement:g,htmlContent:c}):g=null):g=null;g&&g.targetElement.html(g.htmlContent)},generateAboutEstimationText:function(c,e){c=f(c,e);return r.aboutUpperCase.replace(l.TEMPLATE_REPLACE_STRING.ESTIMATE,c)},createRegulatoryDisplayDocumentFragment:function(c,
g){if(!e(c,g))return null;c=f(c,g);c=r.aboutUpperCase.replace(l.TEMPLATE_REPLACE_STRING.ESTIMATE,c);c=v.replace(l.TEMPLATE_REPLACE_STRING.REPLACE,c);g=document.createDocumentFragment();var n=document.createElement("div");n.innerHTML=c;g.appendChild(n);return g}}})});"use strict";y.declare("pvw-bs-translations",{summaryDisclaimerText:"The final price will be adjusted based on the actual weight of the items received.",quantitySelectorUnitText:"Item(s)",selectQuantityText:"Select quantity:",estTotalPriceText:"Total est. price:",
estTotalWeightText:"Total est.:",addToCartButtonText:"Add to Cart",updateCartButtonText:"Update cart",cancelMessage:"Cancel",aboutUpperCase:"About {estimate}.",aboutLowerCase:"(about {estimate})",variableWeightDisclaimer:"Final cost by weight.",updateQuantityText:"Update quantity",itemText:"{quantity} item",itemsText:"{quantity} items",addToDeliveryButtonText:"Add {qty} {unit} to delivery"})});
/* ******** */
(function(a){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,b=d?d("PortableOffersDisplayAssets@add-to-cart","PortableOffersDisplayAssets"):c;b.guardFatal?b.guardFatal(a)(b,window):b.execute(function(){a(b,window)})})(function(a,c,d){a.register("pcta:add-to-cart:constants",function(){return{DECLARATIVE_ACTION_NAME:"cta-add-to-cart",METRICS:{AX_LOAD_TIME:"ax:load:time"},PREFIX:"items",ITEM_TYPES:{BASE:"base"},PARAMETER_PATHS:{QUANTITY:["quantity"],GIFTOPTIONS:["additionalParameters",
"giftOptions","includeGiftReceipt"],UOM_QUANTITY_DIMENSION:["unitOfMeasureQuantity","unitOfMeasure","dimension"],UOM_QUANTITY_UNIT:["unitOfMeasureQuantity","unitOfMeasure","unit"],UOM_QUANTITY_VALUE:["unitOfMeasureQuantity","value"]},ELEMENTS:{AX_ATC:".ax-atc",AX_FACEOUT_CONTAINER:".atc-faceout-container"},BUILD_TIME_CONSTANT:"build-change-v1"}});"use strict";a.when("A","pcta:add-to-cart:constants","cta-handler","pcta:utils:csm").register("pcta:add-to-cart:handler",function(b,a,c,f){b.declarative(a.DECLARATIVE_ACTION_NAME,
"click",function(a){c.handleCTAClick(a)});f.logPerformance(a.METRICS.AX_LOAD_TIME)});"use strict";a.when("A","pcta:add-to-cart:constants").register("pcta:atc-parameter-name",function(a,c){return{constructParameterName:function(a,b,d){if("string"===typeof a&&"number"===typeof b&&0<=b&&Array.isArray(d)){var e=c.PREFIX;e+="["+(b+"."+a)+"]";d.forEach(function(a){e+="["+a+"]"});return e}console.debug("pctaLogFatalsEvent","[Invalid parameters used to construct add to cart parameter]","WARN","addtocart_construct_parameter_error")}}})});
/* ******** */
(function(e){var m=window.AmazonUIPageJS||window.P,g=m._namespace||m.attributeErrors,c=g?g("PortableOffersDisplayAssets@variable-weight","PortableOffersDisplayAssets"):m;c.guardFatal?c.guardFatal(e)(c,window):c.execute(function(){e(c,window)})})(function(e,m,g){e.register("pcta:vw-constants",function(){return{DECLARATIVE_ACTIONS:{VW_PRE_ACTION:"pcta-pre-action-vw",VW_SPIN_BUTTON_CLICK:"a-stepper-spinbutton",VW_CHEVRON_CLICK:"a-stepper-chevron",VW_ATC_CLICK:"pvw-bs-atc-click"},ELEMENTS:{VW_PRE_ACTION:"[data-pcta-pre-action-vw]",
AX_VUOM:".ax-vuom"},PVW_BOTTOM_SHEET:"pvw_bottom_sheet",DIMENSION:{WEIGHT:"WEIGHT",COUNT:"COUNT"},UNITS:{UNIT:"UNIT"},EVENTS:{AX_ATC:"ax:atc",AX_QS_UPDATE:"ax:qs:update"}}});"use strict";e.when("A","ax:initiator","pcta:vw-constants","pcta:vw-util","pvw-drop-down","pvw-text-replace").register("pcta-preaction-vw-static",function(c,e,a,f,h,g){function k(d){var l=f.getMetaInfoForOpeningSheet(d);if(l){var a=d.$target.closest(".atc-faceout-container"),b=a.find("form"),p=a.find(".pvw-dropdown-container");
a=a.attr("data-asin");h.openDropdown(l,function(b){c.trigger("a:stepper:value:change",{$stepperElement:f.getStepperElement(d),newValue:b})},b,p,a)}}function n(d){var a=f.getMetaInfoForAxEvent(d);a&&g.replaceRegulatoryText(d.quantity,d.$faceoutContainer,a)}c.declarative(a.DECLARATIVE_ACTIONS.VW_PRE_ACTION,"click",function(a){a.$event.preventDefault();var c=a.$target.closest(".atc-faceout-container"),d=c.find("form"),b=c.find(".pvw-dropdown-container");c=c.attr("data-asin");h.openDropdown(a.data,function(b){b=
f.createRequestPayload(a,b);e.initiateCTAHandling(a,b)},d,b,c)});c.declarative(a.DECLARATIVE_ACTIONS.VW_CHEVRON_CLICK,"click",k);c.declarative(a.DECLARATIVE_ACTIONS.VW_SPIN_BUTTON_CLICK,"click",k);c.on(a.EVENTS.AX_ATC,function(a){n(a)});c.on(a.EVENTS.AX_QS_UPDATE,function(a){n(a)})});"use strict";e.when("A","a-stepper","pcta:vw-constants","pcta:add-to-cart:constants","pcta:atc-parameter-name","action-handler:dom-input-parser").register("pcta:vw-util",function(c,e,a,f,h,m){function k(b){b=b.find(a.ELEMENTS.AX_VUOM);
return 0<b.length?b.data().vuom:g}function n(b){b=b.find(a.ELEMENTS.VW_PRE_ACTION);return 0<b.length?b.data().pctaPreActionVw:g}function d(b){var a=b.siblings(f.ELEMENTS.AX_ATC),c=b.closest(f.ELEMENTS.AX_FACEOUT_CONTAINER);if(a=n(a)||k(c))b=e.getStepper(b),a.currentQuantity=b.getValue();return a}function l(b){return q(b.$event.currentTarget).closest("[data-a-component\x3dstepper]")}var q=c.$;return{getMetaInfoForOpeningSheet:function(b){b=l(b);return d(b)},getStepperElement:l,createRequestPayload:function(b,
c,d){var e=m.createRequestPayload(b);d=d||b&&b.data;b=d.isItemSoldByCount;d=d.sellingUnitOfMeasureUnit;var g=h.constructParameterName(f.ITEM_TYPES.BASE,0,f.PARAMETER_PATHS.QUANTITY),p=h.constructParameterName(f.ITEM_TYPES.BASE,0,f.PARAMETER_PATHS.UOM_QUANTITY_DIMENSION),k=h.constructParameterName(f.ITEM_TYPES.BASE,0,f.PARAMETER_PATHS.UOM_QUANTITY_UNIT),l=h.constructParameterName(f.ITEM_TYPES.BASE,0,f.PARAMETER_PATHS.UOM_QUANTITY_VALUE);e[g]=b?c:1;e[p]=b?a.DIMENSION.COUNT:a.DIMENSION.WEIGHT;e[k]=d||
a.UNITS.UNIT;e[l]=c;return e},getMetaInfoForAxEvent:function(b){var a=b.$faceoutContainer,c=a.find(f.ELEMENTS.AX_ATC);if(a=n(c)||k(a))a.currentQuantity=b.quantity;return a},getMetaInfoFromStepperElement:d}})});
/* ******** */
(function(k){var l=window.AmazonUIPageJS||window.P,u=l._namespace||l.attributeErrors,c=u?u("PortableOffersDisplayAssets@add-to-delivery","PortableOffersDisplayAssets"):l;c.guardFatal?c.guardFatal(k)(c,window):c.execute(function(){k(c,window)})})(function(k,l,u){k.register("pcta:add-to-delivery:constants",function(){return{ADD_DECLARATIVE_ACTION_NAME:"cta-add-to-delivery",UNDO_DECLARATIVE_ACTION_NAME:"undo-add-to-delivery",SPINNER_CLASS_NAME:"ax-atc-spinner",THREE_DOT_LOADER:"three-dot-loader",HIDDEN_CLASS:"aok-hidden",
STEPPER_CLASS:"add-to-delivery-stepper",ADD_TO_DELIVERY_FORM_CLASS:"add-to-delivery-form",DESKTOP_QUANTITY_DROPDOWN_ID:"quantity",DATA_ATD_STATE_ID_ATTRIBUTE:"data-atd-state-id",STEPPER_SPINBUTTON_SELECTOR:'[data-action\x3d"a-stepper-spinbutton"]',VW_ATD_SELLINGMIN_PARAM:"sellingMin",METRICS:{AX_LOAD_TIME:"ax:load:time:atd",AX_BUTTON_RENDER_COUNT:"ax:atd:button:render",AX_BUTTON_CLICK_COUNT:"ax:atd:button:click",VW_ATD_ITEM_DETECTED:"vw_atd_item_detected",VW_ATD_STEPPER_REQUESTED:"vw_atd_stepper_requested",
VW_ATD_BOTTOM_SHEET_OPENED:"vw_atd_bottom_sheet_opened",VW_ATD_MODIFICATION_CONFIRMED:"vw_atd_modification_confirmed",VW_ATD_METADATA_MISSING_ON_CARET_CLICK:"vw_atd_metadata_missing_on_caret_click"},ADD_TO_DELIVERY_QUANTITY_STEPPER_INCREMENT_ACTION_NAME:"cta-add-to-delivery-quantity-stepper-increment",ADD_TO_DELIVERY_QUANTITY_STEPPER_DECREMENT_ACTION_NAME:"cta-add-to-delivery-quantity-stepper-decrement"}});"use strict";k.when().register("pcta:atd:vw-exclude-configuration",function(){return{isVWEnabled:function(){return!1}}});
"use strict";k.when("A","a-button","pcta:add-to-delivery:constants","cta-handler","ax:add-to-delivery:quantity-stepper:helper","ax:add-to-delivery:atd-helper-functions","pcta:utils:csm","ax:util:logger","pcta:atd:vw-exclude-configuration","ax:vw-atd:metadata-parser","pcta:vw-util").register("pcta:add-to-delivery:handler",function(c,e,b,l,v,h,f,A,m,p,E){function u(a){var d=[];a=c.$('input[name\x3d"asin"][value\x3d"'+a+'"]');if(!a||!a.length)return d;a.each(function(a,b){d.push(c.$(b).parent().find(".add-to-delivery-button"))});
return d}function y(a,b){return b?u(b):a?(a=a.$declarativeParent.find(".add-to-delivery-button"))?[a]:[]:[]}function L(a){a&&a.forEach(function(a){var c=a.find(".a-button-text");c.length&&!a.find(".a-button-inner").find("."+b.THREE_DOT_LOADER).length&&(a.data("original-text")||a.data("original-text",c.html().trim()),a.find(".a-button-inner").append('\x3cspan class\x3d"'+b.THREE_DOT_LOADER+' centered-loader aok-hidden"\x3e\x3c/span\x3e'),c.css("visibility","hidden"),a.find(".a-button-inner").find("."+
b.THREE_DOT_LOADER).removeClass("aok-hidden"))})}function M(a,c){a&&c&&a.forEach(function(a){var d=a.find(".a-button-text");if(d.length){var g=a.closest(".a-declarative"),e=g.data("cta-add-to-delivery");if(e&&e.addMoreToDeliveryPlusText){var f=a.data("original-text")||d.html().trim();g=(g=g.attr(b.DATA_ATD_STATE_ID_ATTRIBUTE))&&""!==g?!!v.getElement(g):!1;c!==b.ADD_DECLARATIVE_ACTION_NAME||g?d.html(f):d.html(e.addMoreToDeliveryPlusText)}a.find(".a-button-inner").find("."+b.THREE_DOT_LOADER).remove();
d.css("visibility","visible")}})}function w(){G();v.disableAllSteppers();L(y(r,x))}function G(){var a=e(".add-to-delivery-button");a&&a.disable();(a=e("#add-to-delivery-button"))&&a.disable()}function q(a){n=!1;var b=e('.add-to-delivery-button:not([data-permanently-disabled\x3d"true"])');b&&b.enable();(b=e("#add-to-delivery-button"))&&b.enable();v.enableAllSteppers();a&&M(y(r,x),a)}function B(a){x=a&&a.requestPayload&&a.requestPayload.inputs&&a.requestPayload.inputs.asin?a.requestPayload.inputs.asin:
null}function N(a){c.$("."+b.ADD_TO_DELIVERY_FORM_CLASS).each(function(){var b=c.$(this).find('input[name\x3d"quantity"]');b.length&&b.val(a)})}function H(a){if(!a||!m.isVWEnabled())return!1;try{var d=a.$declarativeParent&&a.$declarativeParent.data("cta-add-to-delivery");!d&&a.$target&&(d=c.$(a.$target).closest("[data-cta-add-to-delivery]").data("cta-add-to-delivery"));return d?d.formAction&&-1!==d.formAction.indexOf(b.VW_ATD_SELLINGMIN_PARAM+"\x3d")||a.$target&&c.$(a.$target).closest("form").find('input[name\x3d"'+
b.VW_ATD_SELLINGMIN_PARAM+'"]').length||a.$declarativeParent&&a.$declarativeParent.find('input[name\x3d"'+b.VW_ATD_SELLINGMIN_PARAM+'"]').length?!0:!1:!1}catch(g){return!1}}function C(a){if(!a||!m.isVWEnabled())return null;try{return p.extractVWMetadata(a)||null}catch(d){return null}}function z(a,c,g){k.now("ax:call-to-action:add-to-delivery:state-manager").execute(function(d){d&&d.dispatch?k.now("ax:call-to-action:add-to-delivery:intra-purchase-handler").execute(function(b){var e=h.getOrCreateAtdStateId(a),
f=c||h.extractAllParameters(a),k=h.generateDeliveryIdentifier(f);d.dispatch({type:"ADD_TO_DELIVERY_INTRA_PURCHASE_CLICK",offerListing:{atdStateId:e,params:f,deliveryIdentifier:k,vwConfig:g||null}});d.dispatch(b.reconcileClientAndServerStates)}):(D+=1,f.logCounterWithPageContext(b.METRICS.AX_BUTTON_CLICK_COUNT+":"+D,1),l.handleCTAClick(a))})}function I(a,d){c.capabilities.mobile&&(n=!1,f.logCounter(b.METRICS.VW_ATD_BOTTOM_SHEET_OPENED,1),k.now("pvw-bottom-sheet").execute(function(c){try{c.openSheet(Object.assign({},
a,{mode:"atd"}),function(c){f.logCounter(b.METRICS.VW_ATD_MODIFICATION_CONFIRMED,1);n=!0;w();c=E.createRequestPayload(d,c,a);z(d,c,a)})}catch(F){A.logError(F,"VW AtD: Failed to open VW bottom sheet for modification",F.message,"FATAL"),n=!1,q()}}))}function J(a){0<c.$(".add-to-delivery-button").length&&!K&&(K=!0,document.addEventListener("click",function(a){n&&(a.preventDefault(),a.stopPropagation())},!0));var d=c.$(a.$target).closest(".a-button");if(!d.length||"true"!==d.attr("data-permanently-disabled")){var g=
void 0;d.length&&d.hasClass("add-to-delivery-button")?g=e(".add-to-delivery-button"):d.length&&(d.attr("id","add-to-delivery-button"),g=e("#add-to-delivery-button"));if(!g.isEmpty()&&!d.hasClass("a-button-disabled")&&(r=a,n=!0,d.length)){t=d[0];if(H(a)&&(d=C(a))){f.logCounter(b.METRICS.VW_ATD_ITEM_DETECTED,1);g=E.createRequestPayload(a,d.sellingMin,d);z(a,g,d);f.logCounter(b.METRICS.VW_ATD_STEPPER_REQUESTED,1);return}z(a,null)}}}function O(a){if(r)return r;a=c.$(a.$target).closest("."+b.STEPPER_CLASS).siblings("[data-cta-add-to-delivery]");
return a.length?{$declarativeParent:a,$target:a,$currentTarget:a}:null}var n=!1,t=null,r=null,x=null,K=!1,D=0;0<c.$(".add-to-delivery-button").length&&(f.logCounter(b.METRICS.AX_BUTTON_RENDER_COUNT,1),f.logCounterWithPageContext(b.METRICS.AX_BUTTON_RENDER_COUNT,1));c.declarative(b.ADD_DECLARATIVE_ACTION_NAME,"click",J);c.declarative(b.UNDO_DECLARATIVE_ACTION_NAME,"click",function(a){D=0;l.handleCTAClick(a)});c.on("ax:exp:"+b.ADD_DECLARATIVE_ACTION_NAME+":beforeExecution",function(a){B(a);w()});c.on("ax:exp:"+
b.ADD_DECLARATIVE_ACTION_NAME+":afterExecution",function(){q(b.ADD_DECLARATIVE_ACTION_NAME)});c.on("ax:exp:"+b.ADD_DECLARATIVE_ACTION_NAME+":fallback",function(){q(b.ADD_DECLARATIVE_ACTION_NAME+":fallback")});c.on("ax:bottomSheet:closed",function(){q();var a=document.querySelector("button.a-ccs-sheet-close.a-sheet-ccs-close-type-icon");if(a)setTimeout(function(){a.focus()},100);else if(t){if("detail"===f.getPageTypeForMetrics()){var d=c.$(t).closest(".a-declarative"),g=d.find(".add-to-delivery-button");
d=d.siblings("."+b.STEPPER_CLASS);g.hasClass(b.HIDDEN_CLASS)&&d.length?(g=d.find(b.STEPPER_SPINBUTTON_SELECTOR),g.length&&(g.attr("tabindex","-1"),g[0].focus())):(t.setAttribute("tabindex","0"),t.focus())}x=r=null}});c.on("ax:exp:"+b.UNDO_DECLARATIVE_ACTION_NAME+":beforeExecution",function(a){n=!0;if(a&&a.requestPayload&&a.requestPayload.inputs&&a.requestPayload.inputs.formAction)var b=(a=a.requestPayload.inputs.formAction.match(/atdStateId=([^&]+)/))?a[1]:null;k.now("ax:call-to-action:add-to-delivery:state-manager").execute(function(a){a&&
a.dispatch&&b&&a.dispatch({type:"STARTED_RECONCILE",stateIdsUndergoingUpdate:[b]})});w()});c.on("ax:exp:"+b.UNDO_DECLARATIVE_ACTION_NAME+":afterExecution",function(){q(b.UNDO_DECLARATIVE_ACTION_NAME)});c.on("ax:exp:"+b.ADD_TO_DELIVERY_QUANTITY_STEPPER_INCREMENT_ACTION_NAME+":afterExecution",function(){q(b.ADD_TO_DELIVERY_QUANTITY_STEPPER_INCREMENT_ACTION_NAME)});c.on("ax:exp:"+b.ADD_TO_DELIVERY_QUANTITY_STEPPER_DECREMENT_ACTION_NAME+":afterExecution",function(){q(b.ADD_TO_DELIVERY_QUANTITY_STEPPER_DECREMENT_ACTION_NAME)});
c.on("ax:exp:"+b.UNDO_DECLARATIVE_ACTION_NAME+":fallback",function(){q(b.UNDO_DECLARATIVE_ACTION_NAME+":fallback")});c.on("ax:actionProcessing:reset",function(){n=!1});c.on("ax:exp:"+b.ADD_TO_DELIVERY_QUANTITY_STEPPER_INCREMENT_ACTION_NAME+":beforeExecution",function(a){B(a);n=!0;w()});c.on("ax:exp:"+b.ADD_TO_DELIVERY_QUANTITY_STEPPER_DECREMENT_ACTION_NAME+":beforeExecution",function(a){B(a);n=!0;w()});c.declarative("a-stepper-spinbutton","click",function(a){var b=O(a);if(H(b)){var c=C(b);if(c){var e=
h.getOrCreateAtdStateId(b);k.now("ax:call-to-action:add-to-delivery:state-manager").execute(function(a){a&&a.dispatch&&a.dispatch({type:"ATD_VW_WHEEL_OPEN",atdStateId:e,vwConfig:c,event:b})})}}});c.on("ax:atd:vw-wheel:open",function(a){a&&a.vwConfig&&I(a.vwConfig,a.event)});c.on("ax:atd:snappy-qs:debounce-started",function(a){a&&a.asin&&(x=a.asin);G()});(function(){c.$("#"+b.DESKTOP_QUANTITY_DROPDOWN_ID).change(function(){var a=c.$(this).val();a&&N(a)})})();f.logPerformance(b.METRICS.AX_LOAD_TIME);
f.logPerformanceWithPageContext(b.METRICS.AX_LOAD_TIME);return{addToDelivery:J,updateLastFocusedElement:function(a){a&&(t=a)},openVWBottomSheetForModification:I,executeAtDAction:z,getVWMetadataForAtD:C}});"use strict";k.register("pcta:icdp-add-to-delivery:constants",function(){return{ADD_DECLARATIVE_ACTION_NAME:"icdp-cta-add-to-delivery",METRICS:{AX_LOAD_TIME:"ax:load:time:atd:icdp",MISSING_NOTIFY_CONTAINER_EVENT:"ax:atd:icdp:missing:notify:container:event",PARENT_MISSING_AX:"ax:atd:icdp:parent:missing:ax",
RESET_QUANTITY_STEPPER_ERROR:"ax:atd:icdp:reset:atc:qs:error",QUANTITY_STEPPER_TIMEOUT:"ax:atd:icdp:reset:atc:qs:timeout"},CONTAINER_EVENT:{NOTIFY:"icdp-page-notify-container",CLOSE_SHEET:"icdp-close-sheet",CLOSE_SHEET_AND_EXECUTE_CTA_HANDLER:"icdp-close-sheet-and-execute-cta-handler"},AX_QUANTITY_STEPPER:{SELECTOR:{FIELDSET:'[name\x3d"ax-qs"]',FORM:'form[id\x3d"addToCart"]'},DATA:{QUANTITY:"data-steppervalue",ASIN:"data-asin"},INPUT:{OFFER_LISTING_ID:'input[name\x3d"items[0.base][offerListingId]"]'},
EVENT:{VALUE_CHANGE:"a:stepper:value:change",UPDATE:"ax:qs:update",COMPLETE:"icdp:ax:qs:update:complete"},TIMEOUT:2E3}}});"use strict";k.when("A","pcta:add-to-delivery:constants","pcta:icdp-add-to-delivery:constants","pcta:icdp-atc-qs-helper","pcta:add-to-delivery:handler","pcta:utils:csm","pcta:utils:iframe","action-handler:dom-input-parser").register("pcta:icdp-add-to-delivery:handler",function(c,e,b,k,v,h,f,A){c.declarative(b.ADD_DECLARATIVE_ACTION_NAME,"click",function(m){if(c.isListening(b.CONTAINER_EVENT.NOTIFY)){m.action=
e.ADD_DECLARATIVE_ACTION_NAME;var p=A.createRequestPayload(m);f.isIframe()?f.isCTAHandlerOnParentWindow()?function(){var e=function y(){c.off(b.AX_QUANTITY_STEPPER.EVENT.COMPLETE,y);c.trigger(b.CONTAINER_EVENT.NOTIFY,{eventName:b.CONTAINER_EVENT.CLOSE_SHEET_AND_EXECUTE_CTA_HANDLER,arguments:{event:m,inputPayload:p}})};m.$event.preventDefault();m.$event.stopPropagation();l&&l.parent&&l.parent.P&&l.parent.P.now("ax:call-to-action:add-to-delivery:state-manager").execute(function(b){b&&b.dispatch&&b.dispatch({type:"ADD_TO_DELIVERY_CLICK"})});
c.on(b.AX_QUANTITY_STEPPER.EVENT.COMPLETE,e);c.delay(function(){c.isListening(b.AX_QUANTITY_STEPPER.EVENT.COMPLETE)&&(h.logCounter(b.METRICS.QUANTITY_STEPPER_TIMEOUT,1),e())},b.AX_QUANTITY_STEPPER.TIMEOUT)}():(h.logCounter(b.METRICS.PARENT_MISSING_AX,1),h.logCounterWithPageContext(b.METRICS.PARENT_MISSING_AX,1),c.trigger(b.CONTAINER_EVENT.NOTIFY,{eventName:b.CONTAINER_EVENT.CLOSE_SHEET})):v.addToDelivery(m);k.resetQuantityStepper(p)}else h.logCounter(b.METRICS.MISSING_NOTIFY_CONTAINER_EVENT,1),h.logCounterWithPageContext(b.METRICS.MISSING_NOTIFY_CONTAINER_EVENT,
1)});h.logPerformance(b.METRICS.AX_LOAD_TIME);h.logPerformanceWithPageContext(b.METRICS.AX_LOAD_TIME)});"use strict";k.when("A","pcta:icdp-add-to-delivery:constants","pcta:utils:csm").register("pcta:icdp-atc-qs-helper",function(c,e,b){function k(){function b(){c.trigger(e.AX_QUANTITY_STEPPER.EVENT.COMPLETE);c.off(e.AX_QUANTITY_STEPPER.EVENT.UPDATE,b)}c.on(e.AX_QUANTITY_STEPPER.EVENT.UPDATE,b)}return{resetQuantityStepper:function(l){try{(function(){var b=!1;c.$(e.AX_QUANTITY_STEPPER.SELECTOR.FIELDSET).each(function(){var f=
c.$(this),h;if(h=!b){h=l.asin;var m=l.offeringID,p=f.closest(e.AX_QUANTITY_STEPPER.SELECTOR.FORM);h=f.attr(e.AX_QUANTITY_STEPPER.DATA.ASIN)===h&&p&&p.find(e.AX_QUANTITY_STEPPER.INPUT.OFFER_LISTING_ID)&&p.find(e.AX_QUANTITY_STEPPER.INPUT.OFFER_LISTING_ID).val()===m}h&&(b=!0,k(),h=parseFloat(l.quantity),m=parseFloat(f.attr(e.AX_QUANTITY_STEPPER.DATA.QUANTITY)),c.trigger(e.AX_QUANTITY_STEPPER.EVENT.VALUE_CHANGE,{$stepperElement:f,newValue:Math.max(m-h,0)}))});b||c.trigger(e.AX_QUANTITY_STEPPER.EVENT.COMPLETE)})()}catch(h){b.logCounter(e.METRICS.RESET_QUANTITY_STEPPER_ERROR,
1),c.trigger(e.AX_QUANTITY_STEPPER.EVENT.COMPLETE)}}}})});
/* ******** */
