'use strict';(function(c){var k=window.AmazonUIPageJS||window.P,m=k._namespace||k.attributeErrors,b=m?m("NileInlineCustomerExperienceWidgetDPXAssets",""):k;b.guardFatal?b.guardFatal(c)(b,window):b.execute(function(){c(b,window)})})(function(c,k,m){c.now("nile-inline-state-utils").execute(function(b){b||c.when("A").register("nile-inline-state-utils",function(b){return{getState:function(g){var n=b.state(g);if(n)return n;b.state.parse();return b.state(g)}}})});c.now("nile-inline-widget-instrumentation").execute(function(b){b||
c.when("nile-inline-state-utils").register("nile-inline-widget-instrumentation",function(b){function g(a){var d=Array.from(arguments).slice(1,arguments.length);return function(){for(var e=arguments.length,f=Array(e),h=0;h<e;h++)f[h]=arguments[h];a.apply(void 0,d.concat(f))}}function n(a){a=[a.dataset.blueMetrics,a.dataset.actionId];a=a.filter(function(a){return a!==m&&null!==a&&""!==a});return a.join(":")}function c(a){for(var d=Object.keys(a),e=0;e<d.length;e++){var f=d[e],h=a[f];null===h||h===m?
h="":"number"===typeof h&&(h=h.toString());a[f]=h}return a}function p(a,d){var e=(e=document.cookie.match(/(?:^|;)\s*amzn-app-id\s*=\s*([^\s;]+)/))?e[1].split("/"):[];var f=/(?:^|;)\s*micron\s*=\s*1\s*(?:$|;)/.test(document.cookie);e={name:e[0],version:e[1],isMicron:f};f=document.cookie.match(/(?:^|;)\s*amzn-app-ctxt\s*=\s*\d\.\d?\s*([^\s;]+)/);try{var h=f?JSON.parse(decodeURIComponent(f[1])):""}catch(C){h=""}f=b.getState("dpx-nice-state");a=Object.assign({timestamp:l(new Date),producerId:"mshop-nile",
metadata:'{"program":"'+(f&&f.instrumentationConfig&&f.instrumentationConfig.programOverride||"blue-dpx")+'"}',isBeta:!1,deviceTypeId:h&&h.di&&h.di.dti||"",directedCustomerId:f&&f.directedCustomerId||"",appVersion:e&&e.version||"",locale:f&&f.locale||"UNKNOWN",marketplaceId:f&&f.marketplaceId||"UNKNOWN",uxSessionId:"",sessionId:u()||""},a);"undefined"!==typeof ue&&ue.event(c(a),"mshop-nile",d)}function k(a,d){var e=a.luggage,f=e.items[a.key];if(d=d[0])d.isIntersecting?(f.impressingStartAt=new Date,
e.visibleElems.add(f.key)):f.impressingStartAt&&(f.impressingEndAt=new Date,f.reason=null!=d.rootBounds?"SCROLLED_AWAY":"REMOVED",r(a),f.impressingStartAt=null,f.impressingEndAt=null,e.visibleElems.remove(f.key))}function q(a){var d=a.luggage.items[a.key];d.impressingStartAt&&"visible"!==document.visibilityState&&(document.contains(d.elem)&&(d.impressingEndAt=new Date,d.reason="PAGE_HIDDEN",r(a)),document.removeEventListener("visibilitychange",d.pageVisibilityChangeListener))}function v(a,d){a.chunks.addFromEvent(d)}
function w(a,d,e){a.requestEndAt=new Date;d=a.chunks.markAsRendered(d);if(e&&e[0]){var f=e[0].matches("[data-blue-request-id]")&&e[0]||e[0].querySelector("[data-blue-request-id]");if(f)for(a.requestId=f.dataset.blueRequestId,p({schemaId:"mshop.nile.events.4",eventTimeUTC:l(a.requestStartAt),nileRequestId:a.requestId,clickstreamRequestId:null,eventName:"INVOKE_NILE_BACKEND_API",eventDetail:void 0},"mshop.nile.events.4"),e=e.find("[data-blue-metrics]"),f=g(x,a),a.visibilityChangeListenerForLatency=
f,document.addEventListener("visibilitychange",a.visibilityChangeListenerForLatency),f=0;f<e.length;f++){var h=e[f],b=n(h);if(a.items[b])a.items[b].elem=h;else{a.items[b]={key:b,elem:h,name:h.dataset.blueMetrics,detail:h.dataset.actionId};var c=d;p({schemaId:"mshop.nile.latency.6",nileRequestId:a.requestId,elementId:h.dataset.actionId,seqId:c.index,requestStartTimeUTC:l(a.requestStartAt),renderingStartTimeUTC:l(c.renderingStartAt),renderingEndTimeUTC:l(c.renderingEndAt),interruptedTimeUTC:""},"mshop.nile.latency.6")}b=
h={luggage:a,key:b};c=b.luggage.items[b.key];c.elem.observer||(c.elem.observer=new IntersectionObserver(g(k,b),{threshold:.85}),c.elem.observer.observe(c.ghost||c.elem),c.pageVisibilityChangeListener||(c.pageVisibilityChangeListener=g(q,b),document.addEventListener("visibilitychange",c.pageVisibilityChangeListener)));b=h.luggage.items[h.key];b.elem.clickListener||(b.elem.clickListener=g(y,h),b.elem.addEventListener("click",b.elem.clickListener))}}}function z(a,d){a.requestEndAt=new Date;document.removeEventListener("visibilitychange",
a.visibilityChangeListenerForLatency)}function x(a){if("visible"!==document.visibilityState&&!a.requestEndAt){a.interruptedAt=new Date;var d=a.flow.toUpperCase(),e=a.chunks.maybeGetLastRendered();p({schemaId:"mshop.nile.latency.6",nileRequestId:a.requestId,elementId:d,seqId:e?e.index+1:0,requestStartTimeUTC:l(a.requestStartAt),renderingStartTimeUTC:"",renderingEndTimeUTC:"",interruptedTimeUTC:l(a.interruptedAt)},"mshop.nile.latency.6");Object.keys(a.items)}}function r(a){var d=a.luggage;a=d.items[a.key];
p({schemaId:"mshop.nile.impressions.1",nileRequestId:d.requestId,elementId:a.detail||a.name,seqId:a.chunkId||0,requestStartTimeUTC:l(d.requestStartAt),impressionStartTimeUTC:l(a.impressingStartAt),impressionEndTimeUTC:l(a.impressingEndAt),impressionEndReason:a.reason},"mshop.nile.impressions.1")}function y(a){var d=a.luggage.items[a.key];p({schemaId:"mshop.nile.events.4",eventTimeUTC:l(new Date),nileRequestId:a.luggage.requestId,clickstreamRequestId:null,eventName:d.name,eventDetail:d.detail},"mshop.nile.events.4")}
function l(a){return a instanceof Date?a.toISOString():""}function A(a){a=(a=(a=a&&a.event&&a.event.refTarget)&&a.closest("[data-blue-metrics]"))&&a.dataset&&a.dataset.actionId;return/^[a-z][a-z0-9]*(?:_[a-z0-9]+)*_\d_\d+$/.test(a)?a:m}function B(a){return{flow:a.flow,actionId:A(a),chunks:{length:0,addFromEvent:function(a){var d={event:a,renderingStartAt:new Date,index:this.length};a.index=d.index;return[].push.call(this,d)},getFromEvent:function(a){return this[a.index]},maybeGetLastRendered:function(){for(var a=
this.length,e=0;e<a&&this[e].renderingEndAt;e++);return 0===e?null:this[e-1]},markAsRendered:function(a){a=this.getFromEvent(a);a.renderingEndAt=new Date;return a}},requestStartAt:new Date,requestEndAt:null,answer:{},visibleElems:{length:0,add:function(a){this[a]||[].push.call(this,a)},remove:function(a){delete this[a]}},items:{}}}function u(){var a=document.cookie.match(/(?:^|;)\s*session-id\s*=\s*([^\s;]+)/);return a?a[1]:""}var t={};return{executeAndLogMetrics:function(a,d){d=B(d);var e=t.luggage;
e&&(document.removeEventListener("visibilitychange",e.visibilityChangeListenerForLatency),e.answer&&e.answer.observer&&(e.answer.observer.unobserve(e.answer.elem),document.removeEventListener("visibilitychange",e.answer.visibilityChangeListener)));t.luggage=d;d={afterFullRender:g(z,d),beforePillRender:g(v,d),afterPillRender:g(w,d)};a(d)},buildContext:function(a,d){return{flow:a,event:d}}}})});c.now("nile-inline-dpx-desktop-sponsored-click-handler").execute(function(b){b||c.when("A").register("nile-inline-dpx-desktop-sponsored-click-handler",
function(){function b(b){fetch(b,{method:"POST",mode:"no-cors",cache:"no-store"}).then(function(){"undefined"!==typeof ue&&ue.count&&ue.count("RUFUS_DPX_ATF_PILL_CLICK.DESKTOP.SPONSORED_CLICK_URL_SUCCESS",1)}).catch(function(b){"undefined"!==typeof ue&&ue.count&&ue.count("RUFUS_DPX_ATF_PILL_CLICK.DESKTOP.SPONSORED_CLICK_URL_FAILURE",1)})}return{handleSponsoredPillClick:function(c){var g="sponsoredEvergreenPill"===c.data.variant;c=c.data.actionUrl;g&&c&&("undefined"!==typeof ue&&ue.count&&ue.count("RUFUS_DPX_ATF_PILL_CLICK.DESKTOP.SPONSORED",
1),b(c));return g}}})});c.when("A").execute(function(b){function q(b,c){var g,p=new Promise(function(b){g=setTimeout(function(){b("timeout")},c)});b=b();return Promise.race([b,p]).then(function(b){clearTimeout(g);return b})}function g(){return new Promise(function(g){c.when("rufus-eligible").execute(function(){k._dpxRufusConnectRegistered||(k._dpxRufusConnectRegistered=!0,b.declarative("dpx-rufus-connect","click",function(b){b.$currentTarget.find(".ask-pill").length?k.P.now("rufus-handle-expand").execute(function(b){b&&
b("NileRelatedQuestionIngress")}):k.P.when("nile-inline-dpx-desktop-sponsored-click-handler").execute(function(c){var g=c.handleSponsoredPillClick(b);k.P.when("rufus-handle-stream").execute(function(c){c&&(ue&&ue.count&&ue.count("RUFUS_DPX_ATF_PILL_CLICK_SENT_TO_RUFUS_DESKTOP",1),c({qis:g?"NileDPSmidgetSponsoredRelatedQuestionIngress":"What do customers say?"===b.data.query?"NileNDSWDCSRelatedQuestion":"NileRelatedQuestionIngress",query:b.data.query,metricName:"BlueDPXIngress"}))})})}));g("resolved")})})}
function n(){q(g,50).then(function(g){"timeout"===g&&c.now("rufus-eligible").execute("hide-dpx-widget",function(c){c===m&&b.$("#dpx-nice-widget-container").hide(0)})}).catch(function(c){b.$("#dpx-nice-widget-container").hide(0)})}n();b.on("PageRefresh:ATF",n)});c.when("A","nile-inline-widget-instrumentation").execute(function(b,c){(function(){var g=c.buildContext("pills");c.executeAndLogMetrics(function(c){var g={type:"default_pills"};c.beforePillRender(g);c.afterPillRender(g,b.$("#dpx-nice-widget-container"))},
g)})()})});